var DEF={name:"Your Name",title:"Content Manager & Creative Producer",sub:"Fashion, beauty, culture",
intro:"I manage and produce content from first plan to final delivery, for fashion and beauty houses that care how things look and how they run.",
ab1:"I plan, produce and deliver content for fashion and beauty brands. I work between brand teams, photographers, filmmakers, stylists and agencies, and keep projects on time and on tone.",
ab2:"My eye for visual culture shapes what I select and how I brief. The titles on the work are managing and producing, and I say so on every page.",
sides:{c:{h:"Content manager",p:"The thinking and the system: what gets made, for whom, when, and how it performs.",li:["Content strategy and planning","Editorial and social calendars","Copy, captions, interviews","Approvals, reporting, delivery"]},
p:{h:"Creative producer",p:"The making: getting the right people, place and time in one room and the work finished well.",li:["Shoot and film production","Call sheets, casting, logistics","Photographers, stylists, directors","On-set coordination, asset handover"]}},
L:{email:"hello@yourname.com",li:"https://www.linkedin.com/in/your-profile",ig:"https://instagram.com/your-handle"},
per:{h:"Project title",t:"Two or three sentences on why you started it, what it is, and where it stands today.",m:"Started 2026. Ongoing."},
T:{n1:"Work",n2:"Social",n3:"Personal",n4:"About",n5:"Contact",f1:"Content Manager & Creative Producer",f2:"Archive 2026",h1:"Two sides of the work",h2:"Selected work",h3:"Instagram content",h4:"All social content",h5:"Personal project",h6:"Ongoing",w1:"Work",s1:"Instagram",s2:"Content I planned, wrote, coordinated and published for brand accounts. Each tile names the format and my part in it.",s3:"Open on Instagram",a1:"Organised work, seen clearly.",l1:"LinkedIn",l2:"Instagram",l3:"Download CV (PDF)",c1:"For brands, agencies and collaborators",p0:"Personal project",m1:"My role",m2:"Collaborators",n6:"Articles",pi:"Instagram content",lk:"Linked content",h7:"Magazine articles",ar1:"Magazine articles",ar2:"Interviews, essays and features I developed, edited or wrote. Tap a title to read it on the publication's site."},st:{},bw:true,M:{},CAT:[{id:"art",n:"Art"},{id:"fashion",n:"Fashion"},{id:"design",n:"Design"},{id:"architecture",n:"Architecture"},{id:"lifestyle",n:"Lifestyle"},{id:"music",n:"Music"},{id:"cinema",n:"Cinema"},{id:"photography",n:"Photography"}],A:[{id:"a1",t:"Article title",pub:"Magazine name",dt:"2026",cat:"fashion",u:"https://"},{id:"a2",t:"Article title",pub:"Magazine name",dt:"2025",cat:"art",u:"https://"},{id:"a3",t:"Article title",pub:"Magazine name",dt:"2025",cat:"cinema",u:"https://"}]};
var P=[
{id:"rick",s:"b",b:"adidas x Rick Owens",t:"Collection campaign",d:"Photo",y:"2025",r:"Content management, production coordination",
 o:"Shape a campaign content plan that matched the collaboration's severe, sculptural language.",
 role:[["Managed","Content calendar, asset approvals, delivery across channels"],["Produced","Shoot logistics, call sheets, studio and talent scheduling"],["Coordinated","Photographer, stylist, casting, brand and regional teams"],["Contributed","Image selection and sequencing for launch"]],
 c:"Photographer, Stylist, Casting, adidas Brand team"},
{id:"wales",s:"p",b:"adidas x Wales Bonner",t:"Launch film and stills",d:"Video",y:"2026",r:"Content management, coordination",
 o:"Bring a culturally rooted collaboration to audiences through film and still imagery.",
 role:[["Managed","Rollout plan, content approvals, timeline"],["Produced","Film schedule and deliverables"],["Coordinated","Director, producer, agency, brand"],["Contributed","Edit feedback, caption and copy direction"]],c:"Director, Producer, Agency, adidas Brand team"},
{id:"simone",s:"c",b:"adidas x Simone Rocha",t:"Editorial and social rollout",d:"Social",y:"2025",r:"Content management, copy",
 o:"Translate a romantic, tactile collaboration into a cohesive digital story.",
 role:[["Managed","Instagram planning and publishing"],["Produced","Asset requests and cutdowns"],["Coordinated","Community and brand teams"],["Contributed","Captions and story sequencing"]],c:"Photographer, Social team, adidas Brand team"},
{id:"avavav",s:"p",b:"adidas x AVAVAV",t:"Campaign content",d:"Production",y:"2025",r:"Production coordination",
 o:"Deliver playful, fast-moving content to a tight launch window.",
 role:[["Managed","Delivery plan and approvals"],["Produced","On-set coordination"],["Coordinated","Creative team, agency, logistics"],["Contributed","Selects and rollout notes"]],c:"Creative team, Agency, adidas Brand team"},
{id:"ysl",s:"b",b:"YSL Beauty",t:"Beauty content series",d:"Photo",y:"2024",r:"Content management, production",
 o:"Keep a beauty campaign consistent across stills, video and social.",
 role:[["Managed","Content plan across formats"],["Produced","Shoot preparation and delivery"],["Coordinated","Makeup artists, photographer, brand"],["Contributed","Visual references and selects"]],c:"Photographer, Makeup, Brand team"},
{id:"valentino",s:"c",b:"Valentino Beauty",t:"Interview and editorial",d:"Articles",y:"2024",r:"Editorial, content development",
 o:"Develop long-form brand storytelling with a distinct editorial voice.",
 role:[["Managed","Editorial calendar and approvals"],["Produced","Interview logistics"],["Coordinated","Writers, editors, brand"],["Contributed","Copywriting and editing"]],c:"Writer, Editor, Brand team"},
{id:"armani",s:"c",b:"Armani Beauty",t:"Digital content programme",d:"Social",y:"2024",r:"Content management",
 o:"Plan and execute a steady, polished digital presence.",
 role:[["Managed","Monthly planning and reporting"],["Produced","Content execution"],["Coordinated","Creators, brand, agency"],["Contributed","Caption and format ideas"]],c:"Creators, Agency, Brand team"}];
var IG=[["Reel","Launch teaser","Plan, edit notes"],["Carousel","Collection story","Copy, sequencing"],["Post","Campaign still","Publishing"],["Reel","Behind the scenes","Produce, capture"],["Story","Launch day","Plan, publish"],["Carousel","Interview excerpt","Edit, copy"],["Post","Product detail","Planning"],["Reel","Film cutdown","Coordinate"],["Post","Community","Moderate"]];

DEF.P=P;DEF.IG=IG;DEF.SP=[{id:"porsche",n:"Porsche",y:"2026",d:"Instagram content and campaign rollout",u:"https://"},{id:"bmw",n:"BMW",y:"2025",d:"Social content and launch posts",u:"https://"}];
var D=[["All","All"],["c","Content management"],["p","Creative production"]],SL={c:"Content management",p:"Creative production",b:"Content management + production"},G={Managed:"c",Produced:"p",Coordinated:"p",Contributed:"x"},GL={c:"Content management",p:"Creative production",x:"Creative contribution"},f="All";
var BASE=JSON.stringify(window.SITE||null),LOCAL=!window.claude&&/[?&]edit\b/.test(location.search),KEY="portfolio-draft",PREV={};
function src(m){return PREV[m.u]||m.u||"/_blob/"+m.id}
var selp=null,S=JSON.parse(JSON.stringify(DEF)),ed=false,can=false,db,assets,doc,tm,cur,app=document.getElementById("app");
function esc(x){return String(x==null?"":x).replace(/&/g,"&amp;").replace(/</g,"&lt;")}
function get(p){return p.split(".").reduce(function(o,k){return o&&o[k]},S)}
function put(p,v){var a=p.split("."),o=S;for(var i=0;i<a.length-1;i++)o=o[a[i]];o[a[a.length-1]]=v}
function save(){clearTimeout(tm);tm=setTimeout(function(){if(LOCAL){try{localStorage.setItem(KEY,JSON.stringify({base:BASE,S:S}));toast("Saved in this browser. Download content.js to publish.")}catch(x){toast("Could not save")}}else if(doc)doc.set({j:JSON.stringify(S)}).then(function(){toast("Saved")},function(){toast("Could not save")})},500)}
function toast(t,ms){var e=document.getElementById("ts");e.textContent=t;e.style.display="block";clearTimeout(toast.t);toast.t=setTimeout(function(){e.style.display="none"},ms||1600)}
function E(p){var q=S.st&&S.st[p],sy=q?' style="'+(q.c?"color:"+q.c+";":"")+(q.b===1?"font-weight:700;":q.b===0?"font-weight:400;":"")+'"':"";return '<span data-p="'+p+'"'+sy+(ed?' contenteditable="true" class="ed"':'')+'>'+esc(get(p))+'</span>'}
function M(k,label,cls,x){var m=S.M[k],i=m?(m.t=="v"?'<video src="'+esc(src(m))+'" data-a="'+(m.u?"/_blob/"+m.id:"")+'" muted loop autoplay playsinline'+(ed?' controls':'')+'></video>':'<img alt="'+esc(label)+'" src="'+esc(src(m))+'" data-a="'+(m.u?"/_blob/"+m.id:"")+'">'):'<span>'+esc(label)+'</span>';
return '<div class="ph md '+(cls||"")+'" role="img" aria-label="'+esc(label)+'">'+i+(ed?'<div class="bar"><button data-up="'+k+'">'+(m?'Replace':'Upload photo / video')+'</button>'+(m?'<button data-rm="'+k+'">Remove</button>':'')+(x||"")+'</div>':'')+'</div>'}
function ordRows(){return S.ORDER.map(function(o){var p=o.p&&S.P.filter(function(x){return x.id==o.p})[0],q=o.s&&S.SP.filter(function(x){return x.id==o.s})[0];if(!p&&!q)return "";
var side=p?p.s:"c",hide=f!="All"&&side!="b"&&side!=f,y=(p&&p.y)||(q&&q.y)||"",lab=p?SL[p.s]+' &nbsp;/&nbsp; '+esc(p.t)+(q?' &nbsp;/&nbsp; Social media':''):'Social media &nbsp;/&nbsp; '+esc(q.d);
return '<a class="row'+(hide?" hide":"")+'" href="#'+(p?'p-'+p.id:'s-'+q.id)+'"><span class="b serif">'+esc(p?p.b:q.n)+'</span><span class="m">'+esc(y)+'</span><span class="r">'+lab+'</span></a>'}).join("")}
function idx(){var h='<div class="filters">'+D.map(function(d){return '<button data-f="'+d[0]+'" class="'+(d[0]==f?"on":"")+'">'+d[1]+'</button>'}).join("")+'</div>';
if(!ed&&S.ORDER)return h+ordRows();
S.P.forEach(function(p,i){var hide=f!="All"&&p.s!="b"&&p.s!=f,t=ed?"div":"a";h+='<'+t+' class="row'+(hide?" hide":"")+'"'+(ed?'':' href="#p-'+p.id+'"')+'><span class="b serif">'+E("P."+i+".b")+'</span><span class="m">'+E("P."+i+".y")+'</span><span class="r">'+SL[p.s]+' &nbsp;/&nbsp; '+E("P."+i+".t")+(ed?' &nbsp;<a href="#p-'+p.id+'" style="text-decoration:underline">Open page</a> &nbsp;<button data-del="'+i+'" style="text-decoration:underline">Delete</button>':'')+'</span></'+t+'>'});
return h+(ed?'<button class="add" data-add="p">+ Add project</button>':'')}
function sides(){return '<div class="two">'+["c","p"].map(function(k){return '<div><h3 class="serif">'+E("sides."+k+".h")+'</h3><p>'+E("sides."+k+".p")+'</p><ul>'+S.sides[k].li.map(function(_,i){return '<li>'+E("sides."+k+".li."+i)+(ed?' <button data-dli="'+k+'.'+i+'" style="text-decoration:underline">Delete</button>':'')+'</li>'}).join("")+'</ul>'+(ed?'<button class="add" data-ali="'+k+'" style="margin:8px 0 0">+ Add item</button>':'')+'</div>'}).join("")+'</div>'}
function inSP(g){return S.SP.some(function(q){return q.id==g[5]})}
function igPost(u){var m=String(u||"").match(/instagram\.com\/(?:[\w.]+\/)?(p|reel|tv)\/([\w-]+)/);return m?"https://www.instagram.com/"+m[1]+"/"+m[2]+"/":""}
function igEmbed(pl,label){return '<div class="igF"><iframe src="'+esc(pl)+'embed/" title="'+esc(label)+' on Instagram" loading="lazy" scrolling="no" allowtransparency="true" allow="encrypted-media; fullscreen"></iframe></div><a class="igL" href="'+esc(pl)+'" target="_blank" rel="noopener noreferrer">View on Instagram ↗</a>'}
function igGrid(n,pid,emb){var h='<div class="ig'+(emb?' igx':'')+'">',k=0;S.IG.forEach(function(g,i){if(pid!=null&&(pid?g[5]!=pid:inSP(g))||k++>=n)return;var tl=M("ig"+g[3],g[0]+": "+g[1]),u=safe(g[4]),pl=igPost(g[4]);
if(emb&&!ed&&pl&&!S.M["ig"+g[3]]){h+='<div class="igE">'+igEmbed(pl,g[0]+": "+g[1])+'<div class="cap">'+E("IG."+i+".0")+' · '+E("IG."+i+".1")+'<br>'+E("IG."+i+".2")+'</div></div>';return}
h+='<div>'+(ed||u=="#"?tl:'<a href="'+u+'" target="_blank" rel="noopener noreferrer">'+tl+'</a>')+'<div class="cap">'+E("IG."+i+".0")+' · '+E("IG."+i+".1")+'<br>'+E("IG."+i+".2")+(ed?'<br>Post link: '+E("IG."+i+".4")+(S.SP.length?'<br><button data-igp="'+i+'" style="text-decoration:underline">Project: '+esc(inSP(g)?S.SP.filter(function(q){return q.id==g[5]})[0].n:"Other")+' ⟳</button>':'')+' <button data-delig="'+i+'" style="text-decoration:underline">Delete</button>':'')+'</div></div>'});return h+'</div>'}
function homeIg(){if(ed||!S.HOMEIG)return igGrid(3);var o='';S.HOMEIG.forEach(function(sid){var q=S.SP.filter(function(x){return x.id==sid})[0],g=S.IG.filter(function(x){return x[5]==sid&&igPost(x[4])})[0];if(!q||!g)return;
o+='<div class="igE">'+igEmbed(igPost(g[4]),q.n+" "+g[0])+'<div class="cap"><a href="#s-'+esc(q.id)+'" style="color:var(--ink);font-weight:700;font-size:15px">'+esc(q.n)+' →</a></div></div>'});return '<div class="ig igx" style="margin:30px 0">'+o+'</div>'}
function home(){return '<section class="hero"><div><h1 class="serif">'+E("name")+'</h1><p class="t">'+E("title")+'</p><p style="color:var(--mute)">'+E("sub")+'</p></div>'+'</section><p class="intro serif">'+E("intro")+'</p><h2 class="serif" style="margin-bottom:22px">'+E("T.h1")+'</h2>'+sides()+'<h2 class="serif" style="margin-bottom:22px">'+E("T.h2")+'</h2><div id="ix">'+idx()+'</div><h2 class="serif" style="margin:70px 0 0">'+E("T.h3")+'</h2>'+homeIg()+'<a class="row" href="#social"><span class="b serif">'+E("T.h4")+'</span><span class="m">'+S.IG.length+' pieces</span></a><a class="row" href="#articles" style="margin-top:70px"><span class="b serif">'+E("T.h7")+'</span><span class="m">'+S.A.length+' pieces</span></a><a class="row" href="#personal"><span class="b serif">'+E("T.h5")+'</span><span class="m">'+E("T.h6")+'</span></a>'}
function roles(p,i){var o='<dl class="role">';["c","p","x"].forEach(function(g){var rs=p.role.map(function(r,j){return [r,j]}).filter(function(x){return G[x[0][0]]==g});if(rs.length)o+='<h3>'+GL[g]+'</h3>'+rs.map(function(x){var j=x[1];return '<div><dt>'+(ed?'<button data-rk="'+i+'.'+j+'" style="text-decoration:underline">'+x[0][0]+' ⟳</button>':x[0][0])+'</dt><dd>'+E("P."+i+".role."+j+".1")+(ed?' <button data-drole="'+i+'.'+j+'" style="text-decoration:underline">Delete</button>':'')+'</dd></div>'}).join("")});return o+'</dl>'+(ed?'<button class="add" data-arole="'+i+'">+ Add role line</button>':'')}
function gal(p,i,k){return p.g.map(function(g,j){var m=S.M[k+g];return M(k+g,"Image or film",p.gl=="natural"&&m?"gn"+(m.wide?" gnw":""):p.gl=="wide"?"gw":["a","b2","w"][j%3],ed?'<button data-dg="'+i+'.'+j+'">Delete slot</button>':'')}).join("")}
function ytId(u){var m=String(u||"").match(/(?:youtu\.be\/|[?&]v=|\/embed\/|\/shorts\/)([\w-]{11})/);return m?m[1]:""}
function yt(p,i){var L=Array.isArray(p.yt)?p.yt:[p.yt],ids=L.map(ytId).filter(Boolean),P="P."+i+".yt";
return (ids.length?'<div class="yts'+(ids.length>1?' two':'')+'">'+ids.map(function(id,x){return '<div class="yt"><iframe src="https://www.youtube-nocookie.com/embed/'+id+'?rel=0" title="'+esc(p.b)+' video '+(x+1)+'" allow="autoplay; encrypted-media; picture-in-picture; fullscreen" allowfullscreen loading="lazy"></iframe></div>'}).join("")+'</div>':'')+(ed?'<div class="u">YouTube video link'+(L.length>1?'s':'')+' (shows a player on this page): '+(Array.isArray(p.yt)?L.map(function(_,x){return E(P+"."+x)}).join(" · "):E(P))+'</div>':'')}
function socLink(p){var o=(S.ORDER||[]).filter(function(x){return x.p==p.id&&x.s})[0],q=o&&S.SP.filter(function(x){return x.id==o.s})[0];return q&&!ed?'<a class="row" href="#s-'+esc(q.id)+'" style="margin-top:50px"><span class="b serif">Social media: '+esc(q.n)+'</span><span class="m">→</span></a>':''}
function caseBlock(o,P,chKey){var F=[["r","Role"],["c","Team"],["ev","Events"],["pa","Partners"]],has=function(k){return o[k]&&String(o[k]).trim()},did=(o.did||[]).filter(function(x){return String(x).trim()});
var meta=F.filter(function(f){return ed||has(f[0])}).map(function(f){return '<span class="cm"><b>'+f[1]+':</b> '+E(P+f[0])+'</span>'}).join(ed?'<br>':'<span class="cd"> · </span>');
var sec=function(k,l){return ed||has(k)?'<p class="cp"><b>'+l+':</b> '+E(P+k)+'</p>':''};
var dl=ed?'<ul>'+(o.did||[]).map(function(_,x){return '<li>'+E(P+"did."+x)+' <button data-dcd="'+P+x+'" style="text-decoration:underline;font-size:12px">Delete</button></li>'}).join("")+'</ul><button class="add" data-acd="'+P+'" style="margin:6px 0 0">+ Add line</button>':did.length?'<ul>'+(o.did||[]).map(function(x,k){return String(x).trim()?'<li>'+E(P+"did."+k)+'</li>':''}).join("")+'</ul>':'';
var body=sec(chKey,"Challenge")+sec("sg","Strategy")+(ed||did.length?'<p class="cp"><b>What I did:</b></p>'+dl:'');
return meta||body?'<section class="case">'+(meta?'<p class="cmeta">'+meta+'</p>':'')+body+'</section>':''}
function proj(p,i){var n=S.P[(i+1)%S.P.length],k="pr"+p.id,q="P."+i+".";
return '<section style="padding-top:30px"><p class="m" style="color:var(--mute)">'+E(q+"d")+(ed||p.y?', '+E(q+"y"):'')+'</p><h1 class="big serif">'+E(q+"b")+'</h1><p style="font-size:19px;margin-top:8px">'+E(q+"t")+'</p>'+(ed?'<p style="margin-top:14px"><button class="add" data-side="'+i+'">Side: '+SL[p.s]+' (tap to change)</button><button class="add" data-del="'+i+'">Delete project</button></p>':'')+'</section>'+(ed||S.M[k+"h"]?M(k+"h","Hero still or film, 16:9",p.gl=="natural"&&S.M[k+"h"]?"hn":"hw"):'')+yt(p,i)+
caseBlock(p,q,"o")+roles(p,i)+
'<div class="pgrid">'+gal(p,i,k)+'</div>'+(ed?'<button class="add" data-ag="'+i+'">+ Add photo / video</button>':'')+lks(p,i)+socLink(p)+(n!==p?'<a class="row" href="#p-'+n.id+'" style="margin-top:50px"><span class="b serif">Next: '+esc(n.b)+'</span></a>':'<a class="row" href="#work" style="margin-top:50px"><span class="b serif">All work</span></a>')}
function about(){return '<section class="cols" style="padding-top:30px"><div><h1 class="big serif">'+E("T.a1")+'</h1></div><div>'+M("about","Portrait, 4:5","ab")+'<p style="font-size:18px">'+E("ab1")+'</p><p style="margin-top:16px;color:var(--mute)">'+E("ab2")+'</p></div></section><div style="margin-top:70px">'+sides()+'</div>'+links()+(ed?'<div class="lk">Email: '+E("L.email")+'</div>':'<a class="lk" href="mailto:'+esc(S.L.email)+'">Email: '+esc(S.L.email)+'</a>')}
function links(){var c=S.M.cv;return '<a class="lk" href="'+(c?esc(src(c)):'#')+'"'+(c&&!ed?' target="_blank" rel="noopener noreferrer"':'')+'>'+(c?E("T.l3"):'CV (PDF) not uploaded')+'</a>'+(ed?'<div class="u"><button class="add" style="margin:0" data-up="cv">Upload CV PDF</button></div>':'')+
'<a class="lk" href="'+safe(S.L.li)+'">'+E("T.l1")+'</a>'+(ed?'<div class="u">'+E("L.li")+'</div>':'')}
function spCount(c,h){var o=[];if(c||!h)o.push(c+(c==1?" post":" posts"));if(h)o.push(h+(h==1?" highlight":" highlights"));return o.join(" · ")}
function spRows(){var h='';S.SP.forEach(function(q,j){var c=S.IG.filter(function(g){return g[5]==q.id}).length,t=ed?"div":"a";
h+='<'+t+' class="row"'+(ed?'':' href="#s-'+esc(q.id)+'"')+'><span class="b serif">'+E("SP."+j+".n")+'</span><span class="m">'+E("SP."+j+".y")+'</span><span class="r">'+spCount(c,(q.hl||[]).length)+' &nbsp;/&nbsp; '+E("SP."+j+".d")+(ed?' &nbsp;<a href="#s-'+esc(q.id)+'" style="text-decoration:underline">Open page</a> &nbsp;<button data-dsp="'+j+'" style="text-decoration:underline">Delete</button>':'')+'</span></'+t+'>'});
var o=S.IG.filter(function(g){return !inSP(g)}).length;if(o)h+='<'+(ed?'div':'a')+' class="row"'+(ed?'':' href="#s-other"')+'><span class="b serif">Other</span><span class="m"></span><span class="r">'+o+(o==1?' post':' posts')+(ed?' &nbsp;<a href="#s-other" style="text-decoration:underline">Open page</a>':'')+'</span></'+(ed?'div':'a')+'>';
return h+(ed?'<button class="add" data-asp="1">+ Add social project</button>':'')}
function social(){return '<section style="padding-top:30px"><h1 class="big serif" style="margin-bottom:24px">'+E("T.s1")+'</h1><p style="font-size:20px;margin-bottom:40px;max-width:560px">'+E("T.s2")+'</p>'+spRows()+'<a class="lk" href="'+safe(S.L.ig)+'" style="margin-top:60px">'+E("T.s3")+'</a>'+(ed?'<div class="u">Profile link: '+E("L.ig")+'</div>':'')+'</section>'}
function hlCover(h){var m=S.M["hlc"+h.id];if(m)return src(m);for(var x=0;x<h.f.length;x++){m=S.M["hl"+h.id+h.f[x]];if(m&&m.t=="i")return src(m)}return ""}
function hlRow(j){var q=S.SP[j],o="";(q.hl||[]).forEach(function(h,k){var u=safe(h.u),c=hlCover(h),inner='<span class="hlc">'+(c?'<img src="'+esc(c)+'" alt="">':'<i>'+esc((h.t||"•").charAt(0))+'</i>')+'</span><span class="hlt">'+esc(h.t)+'</span>';
if(h.f.length)o+='<button class="hl" data-hlo="'+j+'.'+k+'" aria-label="Play '+esc(h.t)+' stories">'+inner+'</button>';else if(u!="#"&&!ed)o+='<a class="hl" href="'+u+'" target="_blank" rel="noopener noreferrer" aria-label="'+esc(h.t)+' highlight on Instagram">'+inner+'</a>';else if(ed)o+='<span class="hl">'+inner+'</span>'});return o?'<div class="hls">'+o+'</div>':''}
function hlEdit(j){var q=S.SP[j];return '<div style="margin:30px 0"><p style="font-weight:700;color:var(--ac)">Story highlights</p>'+q.hl.map(function(h,k){var P="SP."+j+".hl."+k+".";return '<div style="border-top:1px solid var(--line);padding:14px 0"><div class="u">Title: '+E(P+"t")+'<br>Instagram highlight link (used when there are no stories uploaded): '+E(P+"u")+'</div><div class="ag" style="grid-template-columns:repeat(auto-fill,minmax(160px,1fr))"><div>'+M("hlc"+h.id,"Cover (optional)","hlv")+'<div class="cap">Cover</div></div>'+h.f.map(function(f,x){return '<div>'+M("hl"+h.id+f,"Story "+(x+1)+": photo or video, 9:16","hlv",'<button data-dhf="'+j+'.'+k+'.'+x+'">Delete</button>')+'<div class="cap">Story '+(x+1)+'</div></div>'}).join("")+'</div><button class="add" data-ahf="'+j+'.'+k+'">+ Add story</button><button class="add" data-dhl="'+j+'.'+k+'">Delete highlight</button></div>'}).join("")+'<button class="add" data-ahl="'+j+'">+ Add story highlight</button></div>'}
var SV={};
function svOpen(j,k){var h=S.SP[j]&&S.SP[j].hl[k];if(!h||!h.f.length)return;SV={h:h,i:0,mu:true};document.getElementById("sv").classList.add("on");document.body.style.overflow="hidden";svShow()}
function svShow(){clearTimeout(SV.t);var h=SV.h,m=S.M["hl"+h.id+h.f[SV.i]],b=document.getElementById("svb");
b.innerHTML='<div class="svp">'+h.f.map(function(_,x){return '<i><b style="width:'+(x<SV.i?100:0)+'%"></b></i>'}).join("")+'</div><div class="svh"><span>'+esc(h.t)+'</span><span>'+(m&&m.t=="v"?'<button data-svm="1" aria-label="'+(SV.mu?'Unmute':'Mute')+'">'+(SV.mu?'🔇':'🔊')+'</button>':'')+'<button data-svx="1" aria-label="Close">✕</button></span></div>'+(m?(m.t=="v"?'<video src="'+esc(src(m))+'" playsinline autoplay'+(SV.mu?' muted':'')+'></video>':'<img src="'+esc(src(m))+'" alt="'+esc(h.t)+' story '+(SV.i+1)+'">'):'')+'<button class="svq" data-svp="1" aria-label="Previous story"></button><button class="svn" data-svn="1" aria-label="Next story"></button>';
var bar=b.querySelectorAll(".svp b")[SV.i],v=b.querySelector("video");
if(v){v.ontimeupdate=function(){if(v.duration)bar.style.width=v.currentTime/v.duration*100+"%"};v.onended=svNext;v.onerror=function(){SV.t=setTimeout(svNext,800)}}
else{requestAnimationFrame(function(){requestAnimationFrame(function(){bar.style.transition="width 5s linear";bar.style.width="100%"})});SV.t=setTimeout(svNext,5000)}}
function svNext(){if(!SV.h)return;if(SV.i<SV.h.f.length-1){SV.i++;svShow()}else svClose()}
function svPrev(){if(!SV.h)return;if(SV.i>0)SV.i--;svShow()}
function svClose(){clearTimeout(SV.t);SV={};document.getElementById("sv").classList.remove("on");document.getElementById("svb").innerHTML="";document.body.style.overflow=""}
document.addEventListener("keydown",function(e){if(!SV.h)return;if(e.key=="Escape")svClose();else if(e.key=="ArrowRight")svNext();else if(e.key=="ArrowLeft")svPrev()});
function spMedia(q){var ids=(q.yt||[]).map(ytId).filter(Boolean);return ids.length?'<div class="yts'+(ids.length>1?' two':'')+'" style="margin-top:30px">'+ids.map(function(id,x){return '<div class="yt"><iframe src="https://www.youtube-nocookie.com/embed/'+id+'?rel=0" title="'+esc(q.n)+' video '+(x+1)+'" allow="autoplay; encrypted-media; picture-in-picture; fullscreen" allowfullscreen loading="lazy"></iframe></div>'}).join("")+'</div>':''}
function spLinks(q){var L=(q.links||[]).filter(function(l){return safe(l.u)!="#"});return L.length?'<div style="margin-top:30px">'+L.map(function(l){return '<a class="lk" href="'+safe(l.u)+'" target="_blank" rel="noopener noreferrer">'+esc(l.t)+' ↗</a>'}).join("")+'</div>':''}
function sproj(j){var q=j<0?{id:"",n:"Other"}:S.SP[j],P2="SP."+j+".",n=S.SP.length?S.SP[(j+1)%S.SP.length]:null;
return '<section style="padding-top:30px"><p class="m" style="color:var(--mute)">'+E("T.s1")+(j<0||!q.y&&!ed?'':', '+E(P2+"y"))+'</p><h1 class="big serif">'+(j<0?'Other':E(P2+"n"))+'</h1>'+(j<0?'':'<p style="font-size:19px;margin-top:8px;max-width:640px">'+E(P2+"d")+'</p>'+(ed?'<p class="u" style="margin-top:10px">Account link: '+E(P2+"u")+'</p><button class="add" data-dsp="'+j+'">Delete this project</button>':(safe(q.u)!="#"?'<a href="'+safe(q.u)+'" target="_blank" rel="noopener noreferrer" style="display:inline-block;margin-top:14px;color:var(--ac)">View account ↗</a>':'')))+'</section>'+(j>=0?caseBlock(q,P2,"ch")+hlRow(j)+(ed?hlEdit(j):''):'')+
(j>=0?spMedia(q):'')+igGrid(999,q.id,1)+(ed&&j>=0?'<button class="add" data-addig="'+esc(q.id)+'">+ Add post</button>':'')+(j>=0?spLinks(q):'')+
(n&&!(j>=0&&S.SP.length==1)?'<a class="row" href="#s-'+esc(n.id)+'" style="margin-top:50px"><span class="b serif">Next: '+esc(n.n)+'</span></a>':'')+'<a class="row" href="#social"><span class="b serif">All social projects</span></a>'}
function personal(){return '<section style="padding-top:30px"><p style="color:var(--mute)">'+E("T.p0")+'</p>'+S.PP.map(function(p,i){var q="PP."+i+".";return '<div style="margin-top:60px"><h1 class="big serif">'+E(q+"h")+'</h1>'+(ed||S.M[p.k||"pp"+p.id]?M(p.k||"pp"+p.id,"Own work: image or film, 16:9","pw"):'')+'<p style="color:var(--mute);margin-top:14px">'+E(q+"m")+'</p><p style="font-size:18px;line-height:1.55;max-width:720px;margin-top:30px;white-space:pre-line">'+E(q+"t")+'</p>'+ppIg(p,i)+(ed?'<button class="add" data-dpp="'+i+'">Delete this project</button>':'')+'</div>'}).join("")+(ed?'<button class="add" data-app="1">+ Add personal project</button>':'')+'</section>'}
function ppIg(p,i){var q="PP."+i+".";return '<div style="margin-top:40px"><p style="font-size:14px;font-weight:700;color:var(--ac)">'+E("T.pi")+'</p><p>'+(ed?E(q+"hd")+'<br>Profile link: '+E(q+"iu"):'<a class="lk" href="'+safe(p.iu)+'" target="_blank" rel="noopener noreferrer" style="padding:6px 0">'+E(q+"hd")+' ↗</a>')+'</p><div class="ig igx">'+p.lk.map(function(l,j){var u=q+"lk."+j+".",tile=M("pl"+l.id,"Instagram post"),pl=igPost(l.u);if(!ed&&pl&&!S.M["pl"+l.id])return '<div class="igE">'+igEmbed(pl,l.t||"Post")+(l.t?'<div class="cap">'+E(u+"t")+'</div>':'')+'</div>';return '<div>'+(ed?tile:'<a href="'+safe(l.u)+'" target="_blank" rel="noopener noreferrer">'+tile+'</a>')+'<div class="cap">'+E(u+"t")+(ed?'<br>Link: '+E(u+"u")+' <button data-dpl="'+i+'.'+j+'" style="text-decoration:underline">Delete</button>':'')+'</div></div>'}).join("")+'</div>'+(ed?'<button class="add" data-apl="'+i+'">+ Instagram post</button>':'')+'</div>'}
function hdr(){var K={work:"n1",social:"n2",personal:"n3",about:"n4",contact:"n5",articles:"n6"},n=S.NAV.map(function(k,i){return [k,K[k],i]});document.getElementById("hd").innerHTML=(ed?'<span class="serif" style="font-size:22px">'+E("name")+' <a href="#home" class="go">↗</a></span>':'<a href="#home" class="serif" style="font-size:22px">'+esc(S.name)+'</a>')+'<nav>'+n.map(function(x){return '<a href="#'+x[0]+'" data-n="'+x[0]+'">'+E("T."+x[1])+'</a>'+(ed?'<a href="#'+x[0]+'" class="go" aria-label="Go">↗</a><button data-nv="'+x[2]+'.-1" aria-label="Move left" style="padding:4px 8px;border:1px solid #000">←</button><button data-nv="'+x[2]+'.1" aria-label="Move right" style="padding:4px 8px;border:1px solid #000">→</button>':'')}).join("")+'</nav>';document.getElementById("ft").innerHTML='<span>'+E("T.f1")+'</span><span>'+E("T.f2")+'</span>'}
function ordSort(){if(!S.ORDER)return;var pi={},si={};S.ORDER.forEach(function(o,i){if(o.p)pi[o.p]=i;if(o.s)si[o.s]=i});var by=function(m){return function(a,b){return (a.id in m?m[a.id]:1e3)-(b.id in m?m[b.id]:1e3)}};S.P.sort(by(pi));S.SP.sort(by(si))}
function norm(){if(!S.st)S.st={};var ND=["work","social","personal","about","articles"];S.NAV=(S.NAV||[]).filter(function(k){return ND.indexOf(k)>-1});ND.forEach(function(k){if(S.NAV.indexOf(k)<0)S.NAV.push(k)});S.T=Object.assign({},DEF.T,S.T||{});if(!S.PP)S.PP=[{id:"0",k:"personal",h:S.per.h,t:S.per.t,m:S.per.m}];S.PP.forEach(function(p){if(!p.lk)p.lk=[];if(p.hd==null)p.hd="@yourproject";if(p.iu==null)p.iu="https://instagram.com/"});S.P.forEach(function(p){if(!p.g)p.g=["a","b","w"];if(!p.lk)p.lk=[];if(!p.did)p.did=[]});if(!S.SP)S.SP=JSON.parse(JSON.stringify(DEF.SP));S.SP.forEach(function(q){if(!q.hl)q.hl=[];if(!q.did)q.did=[];q.hl.forEach(function(h){if(!h.f)h.f=[];if(h.u==null)h.u="https://"});if(q.y==null)q.y="2026";if(q.u==null)q.u="https://"});S.IG.forEach(function(g,i){if(!g[3])g[3]=String(i);if(g[4]==null)g[4]="https://";if(g[5]==null)g[5]=S.SP.length?S.SP[i<5?0:S.SP.length-1].id:""})}
var af="All";
function safe(u){u=String(u||"").trim().replace(/^(https?:\/\/)+(?=https?:\/\/)/i,"");if(/^@[\w.]+$/.test(u))u="https://instagram.com/"+u.slice(1);else if(!/^[a-z][a-z0-9+.-]*:/i.test(u)&&/^[\w-]+(\.[\w-]+)+/.test(u))u="https://"+u;return /^https?:\/\/[^\s]+\.[^\s]+/i.test(u)?esc(u).replace(/"/g,"&quot;"):"#"}
function cats(){var h='<div class="filters">';if(ed){h+=S.CAT.map(function(c,i){return '<span>'+E("CAT."+i+".n")+'<button data-dc="'+c.id+'" aria-label="Delete category">×</button></span>'}).join("")+'<button data-ca="1">+ Category</button>'}else{h+='<button data-af="All" class="'+(af=="All"?"on":"")+'">All</button>'+S.CAT.filter(function(c){return S.A.some(function(a){return a.cat==c.id})}).map(function(c){return '<button data-af="'+c.id+'" class="'+(af==c.id?"on":"")+'">'+esc(c.n)+'</button>'}).join("")}return h+'</div>'}
function articles(){var cn=function(id){var c=S.CAT.filter(function(x){return x.id==id})[0];return c?c.n:"Uncategorised"};
return '<section style="padding-top:30px"><h1 class="big serif">'+E("T.ar1")+'</h1><p style="font-size:20px;margin:24px 0 30px;max-width:560px">'+E("T.ar2")+'</p>'+cats()+'<div class="ag'+(ed?'':' igx')+'">'+S.A.map(function(a,i){if(!ed&&af!="All"&&a.cat!=af)return "";var q="A."+i+".",pl=igPost(a.u);
if(!ed&&pl&&!S.M["ar"+a.id])return '<div class="igE"><div class="cap" style="font-size:13px;padding:0 0 8px"><b style="color:var(--ac)">'+esc(cn(a.cat))+'</b>'+(a.t?'<br><span style="font-size:18px;color:var(--ink);font-weight:700">'+esc(a.t)+'</span>':'')+(a.pub||a.dt?'<br>'+esc([a.pub,a.dt].filter(Boolean).join(" · ")):'')+'</div>'+igEmbed(pl,a.t||cn(a.cat))+'</div>';
return '<div>'+(S.M["ar"+a.id]||ed?M("ar"+a.id,"Cover image 4:5","acv"):'')+'<div class="cap" style="font-size:13px;padding-top:10px"><b style="color:var(--ac)">'+esc(cn(a.cat))+'</b>'+(ed?' <button data-ac="'+i+'" style="text-decoration:underline">change category</button>':'')+'<br>'+(ed?'<span style="font-size:18px;color:#000">'+E(q+"t")+'</span>':'<a href="'+safe(a.u)+'" target="_blank" rel="noopener noreferrer" style="font-size:18px;color:#000;font-weight:700;letter-spacing:-.02em">'+E(q+"t")+'</a>')+'<br>'+E(q+"pub")+' · '+E(q+"dt")+(ed?'<br>Link: '+E(q+"u")+' <button data-da="'+i+'" style="text-decoration:underline">Delete</button>':'')+'</div></div>'}).join("")+'</div>'+(ed?'<button class="add" data-aa="1">+ Add article</button>':'')+'</section>'}
function lks(p,i){if(!p.lk.length&&!ed)return "";var em=ed?[]:p.lk.filter(function(l){return l.ty=="Instagram post"&&igPost(l.u)&&!S.M["lk"+l.id]});return '<h2 class="serif" style="margin:60px 0 20px">'+E("T.lk")+'</h2>'+(em.length?'<div class="ig igx" style="margin-bottom:30px">'+em.map(function(l){return '<div class="igE">'+igEmbed(igPost(l.u),l.t||"Instagram post")+'</div>'}).join("")+'</div>':'')+'<div class="ag">'+p.lk.map(function(l,j){if(em.indexOf(l)>-1)return "";var q="P."+i+".lk."+j+".",go=l.ty=="Instagram post"?"View on Instagram":l.ty=="Video link"?"Watch":"Read";return '<div>'+(S.M["lk"+l.id]||ed?M("lk"+l.id,"Thumbnail","acv"):'')+'<div class="cap" style="font-size:13px;padding-top:10px"><b style="color:var(--ac)">'+esc(l.ty)+'</b><br>'+(ed?'<span style="font-size:18px;color:#000">'+E(q+"t")+'</span>':'<a href="'+safe(l.u)+'" target="_blank" rel="noopener noreferrer" style="font-size:18px;color:#000;font-weight:700;letter-spacing:-.02em">'+E(q+"t")+'</a>')+'<br>'+E(q+"s")+(ed?'<br>Link: '+E(q+"u")+' <button data-dlk="'+i+'.'+j+'" style="text-decoration:underline">Delete</button>':'<br><a href="'+safe(l.u)+'" target="_blank" rel="noopener noreferrer" style="color:var(--ac)">'+go+' ↗</a>')+'</div></div>'}).join("")+'</div>'+(ed?['Article','Instagram post','Video link'].map(function(t){return '<button class="add" data-alk="'+i+'.'+t+'">+ '+t+'</button>'}).join(""):"")}
function contact(){return '<section style="padding-top:60px"><p style="font-size:clamp(22px,3.4vw,40px);font-weight:700;letter-spacing:-.02em;word-break:break-word">Email: '+(ed?E("L.email"):'<a href="mailto:'+esc(S.L.email)+'" style="text-decoration:underline;text-underline-offset:6px;text-decoration-thickness:1px">'+esc(S.L.email)+'</a>')+'</p></section>'}
function bar(){document.getElementById("tb").style.display=ed&&selp?"flex":"none";var b=document.getElementById("eb");b.innerHTML=can?(ed?'<button data-bw="1">Images: '+(S.bw===false?'colour':'black &amp; white')+'</button>':'')+(LOCAL&&ed?'<button data-ex="1">Download content.js</button><button data-rs="1">Discard draft</button>':'')+'<button data-edit="1">'+(ed?'Done':'Edit site')+'</button>':""}
function route(){var h=location.hash.slice(1)||"home",v;
if(h.indexOf("s-")==0){var i=h=="s-other"?-1:S.SP.map(function(x){return "s-"+x.id}).indexOf(h);v=i>=0||h=="s-other"?sproj(i):social()}
else if(h.indexOf("p-")==0){var i=S.P.map(function(x){return "p-"+x.id}).indexOf(h);v=i>=0?proj(S.P[i],i):home()}
else v=h=="articles"?articles():h=="social"?social():h=="personal"?personal():h=="about"?about():h=="contact"?about():h=="work"?'<section style="padding-top:30px"><h1 class="big serif" style="margin-bottom:30px">'+E("T.w1")+'</h1><div id="ix">'+idx()+'</div></section>':home();
app.innerHTML=v;document.title=S.name+" | "+S.title;document.body.classList.toggle("col",S.bw===false);hdr();bar();
document.querySelectorAll("[data-n]").forEach(function(a){a.classList.toggle("on",a.dataset.n==h||a.dataset.n=="social"&&h.indexOf("s-")==0||a.dataset.n=="work"&&h.indexOf("p-")==0)})}
function rr(){var y=window.scrollY;route();window.scrollTo(0,y)}
document.addEventListener("focusout",function(e){var p=e.target.dataset&&e.target.dataset.p;if(p&&ed){put(p,e.target.innerText.trim());save()}});
document.addEventListener("paste",function(e){if(ed&&e.target.isContentEditable){e.preventDefault();document.execCommand("insertText",false,(e.clipboardData||window.clipboardData).getData("text/plain"))}});
document.addEventListener("click",function(e){if(ed){var an=e.target.closest("a");if(an&&e.target.closest(".ed"))e.preventDefault()}var t=e.target.closest("button"),d=t&&t.dataset;if(!d)return;
if(d.f){f=d.f;document.getElementById("ix").innerHTML=idx()}
else if(d.ex){var bl=new Blob(["// Site content. Generated by the editor (open index.html?edit), then replace this file in the repo.\nwindow.SITE = "+JSON.stringify(S,null,2)+";\n"],{type:"text/javascript"}),a0=document.createElement("a");a0.href=URL.createObjectURL(bl);a0.download="content.js";document.body.appendChild(a0);a0.click();a0.remove()}
else if(d.rs){if(confirm("Discard your unsaved draft and go back to the published content?")){try{localStorage.removeItem(KEY)}catch(x){}location.reload()}}
else if(d.hlo){var a=d.hlo.split(".");svOpen(+a[0],+a[1])}
else if(d.svn){svNext()}else if(d.svp){svPrev()}else if(d.svx){svClose()}
else if(d.svm){SV.mu=!SV.mu;var vv=document.querySelector("#svb video");if(vv){vv.muted=SV.mu;t.textContent=SV.mu?"🔇":"🔊"}}
else if(d.ahl){S.SP[+d.ahl].hl.push({id:"h"+Date.now(),t:"Highlight",u:"https://",f:[]});save();rr()}
else if(d.dhl){var a=d.dhl.split("."),q1=S.SP[+a[0]],h1=q1.hl[+a[1]];if(confirm("Delete the highlight \""+h1.t+"\"?")){delete S.M["hlc"+h1.id];h1.f.forEach(function(f){delete S.M["hl"+h1.id+f]});q1.hl.splice(+a[1],1);save();rr()}}
else if(d.ahf){var a=d.ahf.split(".");S.SP[+a[0]].hl[+a[1]].f.push("f"+Date.now());save();rr()}
else if(d.dhf){var a=d.dhf.split("."),h2=S.SP[+a[0]].hl[+a[1]];delete S.M["hl"+h2.id+h2.f[+a[2]]];h2.f.splice(+a[2],1);save();rr()}
else if(d.acd){get(d.acd.slice(0,-1)).did.push("");save();rr()}
else if(d.dcd){var a=d.dcd.split("."),x=+a.pop(),o0=get(a.join("."));o0.did.splice(x,1);save();rr()}
else if(d.edit){ed=!ed;selp=null;rr()}
else if(d.bw){S.bw=S.bw===false;save();rr()}
else if(d.up){cur=d.up;document.getElementById("fi").click()}
else if(d.rm){delete S.M[d.rm];save();rr()}
else if(d.add){var id="n"+Date.now();S.P.push({id:id,s:"b",b:"Brand name",t:"Project title",d:"Photo",y:"2026",r:"Your role",o:"Describe the objective in one sentence.",role:[["Managed","What you managed"],["Produced","What you produced"],["Coordinated","Who you coordinated"],["Contributed","What you contributed"]],c:"Collaborators",g:["a","b","w"],lk:[]});save();location.hash="p-"+id}
else if(d.del){if(confirm("Delete this project?")){S.P.splice(+d.del,1);save();location.hash="work";rr()}}
else if(d.side){var p=S.P[+d.side];p.s={c:"p",p:"b",b:"c"}[p.s];save();rr()}
else if(d.addig){S.IG.push(["Post","Title","Your part","n"+Date.now(),"https://",d.addig]);save();rr()}
else if(d.asp){var sid="s"+Date.now();S.SP.push({id:sid,n:"Brand name",y:"2026",d:"What you did for this account",u:"https://"});save();location.hash="s-"+sid}
else if(d.dsp){var q0=S.SP[+d.dsp];if(confirm("Delete "+q0.n+" and all its posts?")){S.SP.splice(+d.dsp,1);S.IG=S.IG.filter(function(g){if(g[5]!=q0.id)return true;delete S.M["ig"+g[3]];return false});norm();save();if(location.hash=="#social")rr();else location.hash="social"}}
else if(d.igp){var g1=S.IG[+d.igp],ids=S.SP.map(function(q){return q.id});g1[5]=ids[(ids.indexOf(g1[5])+1)%ids.length];save();rr()}
else if(d.delig){var g0=S.IG.splice(+d.delig,1)[0];delete S.M["ig"+g0[3]];save();rr()}
else if(d.dli){var a=d.dli.split(".");S.sides[a[0]].li.splice(+a[1],1);save();rr()}
else if(d.ali){S.sides[d.ali].li.push("New item");save();rr()}
else if(d.rk){var a=d.rk.split("."),r=S.P[+a[0]].role[+a[1]],ks=["Managed","Produced","Coordinated","Contributed"];r[0]=ks[(ks.indexOf(r[0])+1)%4];save();rr()}
else if(d.drole){var a=d.drole.split(".");S.P[+a[0]].role.splice(+a[1],1);save();rr()}
else if(d.arole){S.P[+d.arole].role.push(["Managed","Describe this"]);save();rr()}
else if(d.ag){S.P[+d.ag].g.push("x"+Date.now());save();rr()}
else if(d.dg){var a=d.dg.split("."),pp=S.P[+a[0]];delete S.M["pr"+pp.id+pp.g[+a[1]]];pp.g.splice(+a[1],1);save();rr()}
else if(d.app){S.PP.push({id:""+Date.now(),h:"Project title",t:"Describe it.",m:"Year. Status.",lk:[],hd:"@yourproject",iu:"https://instagram.com/"});save();rr()}
else if(d.dpp){var q=S.PP.splice(+d.dpp,1)[0];delete S.M[q.k||"pp"+q.id];save();rr()}
else if(d.b!=null&&selp){(S.st[selp]=S.st[selp]||{}).b=+d.b;save();rr()}
else if(d.c!=null&&selp){S.st[selp]=S.st[selp]||{};if(d.c)S.st[selp].c=d.c;else delete S.st[selp];save();rr()}
else if(d.nv){var a=d.nv.split("."),i=+a[0],j=i+ +a[1];if(j>=0&&j<S.NAV.length){var x=S.NAV[i];S.NAV[i]=S.NAV[j];S.NAV[j]=x;save();rr()}}
else if(d.af){af=d.af;rr()}
else if(d.aa){S.A.push({id:"n"+Date.now(),t:"Article title",pub:"Magazine name",dt:"2026",cat:S.CAT.length?S.CAT[0].id:"",u:"https://"});save();rr()}
else if(d.da){var ar=S.A.splice(+d.da,1)[0];delete S.M["ar"+ar.id];save();rr()}
else if(d.ac){var a2=S.A[+d.ac],ids=S.CAT.map(function(c){return c.id}).concat([""]);a2.cat=ids[(ids.indexOf(a2.cat)+1)%ids.length];save();rr()}
else if(d.ca){S.CAT.push({id:"c"+Date.now(),n:"New category"});save();rr()}
else if(d.dc){S.CAT=S.CAT.filter(function(c){return c.id!=d.dc});S.A.forEach(function(a){if(a.cat==d.dc)a.cat=""});if(af==d.dc)af="All";save();rr()}
else if(d.alk){var k=d.alk.indexOf("."),ty=d.alk.slice(k+1),ig=ty=="Instagram post";S.P[+d.alk.slice(0,k)].lk.push({id:"n"+Date.now(),ty:ty,t:ig?"Post caption":ty=="Video link"?"Video title":"Article title",s:ig?"@account":ty=="Video link"?"Platform":"Magazine name",u:"https://"});save();rr()}
else if(d.apl){S.PP[+d.apl].lk.push({id:"n"+Date.now(),t:"Post caption",u:"https://"});save();rr()}
else if(d.dpl){var b2=d.dpl.split("."),pq=S.PP[+b2[0]],lq=pq.lk.splice(+b2[1],1)[0];delete S.M["pl"+lq.id];save();rr()}
else if(d.dlk){var a=d.dlk.split("."),pl=S.P[+a[0]],lx=pl.lk.splice(+a[1],1)[0];delete S.M["lk"+lx.id];save();rr()}});
document.addEventListener("focusin",function(e){var p=e.target.dataset&&e.target.dataset.p;if(p&&ed){selp=p;document.getElementById("tb").style.display="flex"}});
document.getElementById("cp").addEventListener("change",function(e){if(selp&&ed){S.st[selp]=S.st[selp]||{};S.st[selp].c=e.target.value;save();rr()}});
function prep(fl){var ty=fl.type||"";return new Promise(function(res){
if(ty.indexOf("video")==0||/\.(mov|mp4|m4v)$/i.test(fl.name))return res([fl,{type:ty=="video/webm"?"video/webm":"video/mp4"}]);
if(ty=="application/pdf"||ty=="image/gif"||ty=="image/svg+xml")return res([fl,{type:ty}]);
createImageBitmap(fl).then(function(im){var r=Math.min(1,2400/Math.max(im.width,im.height)),c=document.createElement("canvas");c.width=Math.round(im.width*r);c.height=Math.round(im.height*r);var x=c.getContext("2d");x.fillStyle="#fff";x.fillRect(0,0,c.width,c.height);x.drawImage(im,0,0,c.width,c.height);c.toBlob(function(b){res(b?[b,{type:"image/jpeg"}]:[fl,{type:ty||"image/jpeg"}])},"image/jpeg",.86)},function(){res([fl,{type:ty||"image/jpeg"}])})})}
var ER={too_large:"File is over 20 MB. Compress or trim it and try again.",unsupported_type:"This file type isn't supported. Use JPG, PNG, WebP, MP4 or PDF.",quota_or_state:"Storage is full. Delete unused media.",not_granted:"You don't have permission to upload.",rate_limited:"Too many uploads. Wait a moment.",store_unavailable:"Storage is busy. Try again."};
document.addEventListener("error",function(e){var t=e.target;if(!t||(t.tagName!="IMG"&&t.tagName!="VIDEO"))return;var a=t.dataset.a;if(a&&!t.dataset.t){t.dataset.t="1";t.src=a;return}var p=t.parentNode;t.remove();if(p&&!p.querySelector(".bad")){var b=document.createElement("span");b.className="bad";b.textContent=ed?"Could not display this file. Tap Replace and upload a JPG, PNG or MP4.":"";p.insertBefore(b,p.firstChild)}},true);
document.getElementById("fi").addEventListener("change",function(e){var fl=e.target.files[0],key=cur;e.target.value="";if(!fl)return;if(!assets){toast("Uploads are not available here",4000);return}toast("Uploading "+Math.round(fl.size/1048576*10)/10+" MB...",60000);
(LOCAL?Promise.resolve([fl,{type:fl.type}]):prep(fl)).then(function(p){return assets.upload(p[0],p[1])}).then(function(r){var ct=r.contentType||"";S.M[key]={id:r.id,u:r.url,t:ct.indexOf("video")==0?"v":ct=="application/pdf"?"f":"i"};save();rr();toast(LOCAL?"Now add "+fl.name+" to the images folder in the repo":"Uploaded",LOCAL?6000:1600)},function(er){toast((er&&ER[er.code])||("Upload failed"+(er&&er.code?" ("+er.code+")":"")),6000)})});
if(window.SITE)S=Object.assign(S,window.SITE);
if(LOCAL){try{var dr=localStorage.getItem(KEY);if(dr){dr=JSON.parse(dr);if(dr.base===BASE&&dr.S)S=Object.assign(S,dr.S);else{localStorage.setItem(KEY+"-old",JSON.stringify(dr));localStorage.removeItem(KEY);setTimeout(function(){toast("The site was updated since your last edit, so your old browser draft was set aside. You are now editing the latest version.",8000)},300)}}}catch(x){}can=true;assets={upload:function(b,o){var u="images/"+encodeURIComponent(b.name);PREV[u]=URL.createObjectURL(b);return Promise.resolve({id:b.name,url:u,contentType:o.type})}}}
window.addEventListener("hashchange",function(){svClose();window.scrollTo(0,0);route()});norm();ordSort();route();
(async function(){try{var c=window.claude;if(!c)return;var u=await c.use("user");db=await c.use("db");assets=await c.use("assets");
if(db){doc=db.doc("site/main");var s=await doc.get();if(s.exists){var sv=JSON.parse(s.data().j);if(!sv.PP&&sv.per)sv.PP=[{id:"0",k:"personal",h:sv.per.h,t:sv.per.t,m:sv.per.m}];S=Object.assign(S,sv);norm()}}
can=!!(u&&await u.canEdit()&&db&&assets);route()}catch(x){}})();
