// Site content. Anything set here overrides the defaults in index.html.
// Easiest way to change it: open index.html?edit in a browser, edit the page,
// click "Download content.js", and replace this file with the downloaded one.
window.SITE = {
  "name": "Gvantsa Chanadiri",
  "bw": false,
  "P": [
    {
      "id": "venicebiennale",
      "s": "c",
      "b": "Venice Art Biennale",
      "t": "Video content",
      "d": "Video",
      "y": "",
      "r": "",
      "o": "",
      "role": [],
      "c": "",
      "yt": ["https://youtu.be/75sjBFTLekc", "https://youtu.be/btKha_pmXCw", "https://youtu.be/6Cv28_LKl4E"],
      "g": [],
      "lk": [
        { "id": "venice1", "ty": "Instagram post", "t": "Venice Art Biennale reel", "s": "Instagram", "u": "https://www.instagram.com/reel/CsdsF6zI0PM/" },
        { "id": "venice2", "ty": "Instagram post", "t": "Venice Art Biennale reel", "s": "Instagram", "u": "https://www.instagram.com/reel/Csgl-MwoxVa/" },
        { "id": "venice3", "ty": "Instagram post", "t": "Venice Art Biennale reel", "s": "Instagram", "u": "https://www.instagram.com/reel/Csiv4eGIcxA/" },
        { "id": "venice4", "ty": "Instagram post", "t": "Venice Art Biennale reel", "s": "Instagram", "u": "https://www.instagram.com/reel/Cs3CIaTom_T/" },
        { "id": "venice5", "ty": "Instagram post", "t": "Venice Art Biennale reel", "s": "Instagram", "u": "https://www.instagram.com/reel/Cc29J9toID0/" },
        { "id": "venice6", "ty": "Instagram post", "t": "Venice Art Biennale reel", "s": "Instagram", "u": "https://www.instagram.com/reel/Cc0fCiFIBv7/" },
        { "id": "venice7", "ty": "Instagram post", "t": "Venice Art Biennale reel", "s": "Instagram", "u": "https://www.instagram.com/reel/Ccnxw7NI150/" },
        { "id": "venice8", "ty": "Instagram post", "t": "Venice Art Biennale reel", "s": "Instagram", "u": "https://www.instagram.com/reel/C6Enf7coCw2/" }
      ]
    },
    {
      "id": "afflelou",
      "s": "c",
      "b": "Afflelou Paris",
      "t": "Eyewear campaign",
      "d": "Photo",
      "y": "",
      "r": "",
      "o": "",
      "role": [],
      "c": "",
      "gl": "natural",
      "g": ["1", "2", "3", "4"],
      "lk": [
        { "id": "afflelou1", "ty": "Instagram post", "t": "Afflelou Paris reel", "s": "Instagram", "u": "https://www.instagram.com/reel/CylVX6ML7uK/" },
        { "id": "afflelou2", "ty": "Instagram post", "t": "Afflelou Paris reel", "s": "Instagram", "u": "https://www.instagram.com/reel/CfUJIbBomjg/" }
      ]
    },
    {
      "id": "tommyjeans",
      "s": "b",
      "b": "Tommy Jeans",
      "t": "Campaign content",
      "d": "Photo",
      "y": "",
      "r": "Content strategy and production",
      "o": "",
      "role": [],
      "c": "",
      "gl": "natural",
      "g": ["1"],
      "lk": [
        { "id": "tommyjeans1", "ty": "Instagram post", "t": "Tommy Jeans reel", "s": "Instagram", "u": "https://www.instagram.com/reel/C3Ac39wo3u3/" }
      ]
    },
    {
      "id": "thebodyshop",
      "s": "c",
      "b": "The Body Shop",
      "t": "Video content",
      "d": "Video",
      "y": "",
      "r": "",
      "o": "",
      "role": [],
      "c": "",
      "yt": ["https://youtu.be/bkxummNJVuk", "https://youtu.be/rz-E1WPiv0k", "https://youtu.be/03DNWpoFP8E", "https://youtu.be/4K6jf9dU_U8", "https://youtu.be/n7d7bv15p1Q"],
      "gl": "natural",
      "g": ["1"],
      "lk": []
    },
    {
      "id": "melvita",
      "s": "c",
      "b": "Melvita",
      "t": "Editorial and social media content",
      "d": "Social",
      "y": "2024",
      "r": "Content strategy, editorial and social media content",
      "o": "",
      "role": [],
      "c": "",
      "gl": "natural",
      "g": ["1", "3", "4", "5", "6"],
      "lk": [
        { "id": "melvita1", "ty": "Instagram post", "t": "Melvita reel", "s": "Instagram", "u": "https://www.instagram.com/reel/DK9L8dAtDOD/" },
        { "id": "melvita2", "ty": "Instagram post", "t": "Melvita reel", "s": "Instagram", "u": "https://www.instagram.com/reel/DK_wCg1MHO8/" },
        { "id": "melvita3", "ty": "Instagram post", "t": "Melvita reel", "s": "Instagram", "u": "https://www.instagram.com/reel/DLPMv4iNRjO/" }
      ]
    },
    {
      "id": "erborian",
      "s": "p",
      "b": "Erborian",
      "t": "Beauty campaign",
      "d": "Photo",
      "y": "2024",
      "r": "Creative strategy and production",
      "o": "",
      "role": [],
      "c": "",
      "gl": "natural",
      "g": ["2", "3", "4", "9", "5", "6", "7", "8"],
      "lk": [
        { "id": "erborian1", "ty": "Instagram post", "t": "Erborian reel", "s": "Instagram", "u": "https://www.instagram.com/reel/DRfRPI5ANMr/" }
      ]
    },
    {
      "id": "visa",
      "s": "c",
      "b": "Visa",
      "t": "Video content",
      "d": "Video",
      "y": "2024",
      "r": "Content strategy",
      "o": "",
      "role": [],
      "c": "",
      "yt": ["https://youtu.be/h6c97OslT94", "https://youtu.be/_u-0jIrRos8", "https://youtu.be/O0OU0cRffI0", "https://youtu.be/Dvzh21KFhaA"],
      "gl": "natural",
      "g": ["2", "3", "4", "5", "6", "7", "8", "9"],
      "lk": []
    },
    {
      "id": "mini",
      "s": "b",
      "b": "MINI",
      "t": "Campaign and editorial photography",
      "d": "Photo",
      "y": "2024",
      "r": "Content management and creative production",
      "o": "",
      "role": [],
      "c": "Hammock Magazine",
      "gl": "natural",
      "g": ["1", "2", "3", "4", "7", "8", "5", "10", "11", "12", "9"],
      "lk": []
    },
    {
      "id": "porsche",
      "s": "c",
      "b": "Porsche",
      "t": "Video content",
      "d": "Video",
      "y": "2024",
      "r": "Content management",
      "o": "",
      "role": [],
      "c": "",
      "yt": "https://youtu.be/JdZNGuG9KFU",
      "g": [],
      "lk": []
    },
    {
      "id": "moet",
      "s": "p",
      "b": "Moët & Chandon",
      "t": "Summer campaign: digital art and mood video",
      "d": "Digital art",
      "y": "2020",
      "r": "Campaign artwork, social content",
      "o": "Summer, told through illustrated Moët moments: city nights, rooftop picnics, beach days and celebrations. Nine digital artworks and a mood video for social media.",
      "role": [
        ["Produced", "Nine illustrated scenes for the summer campaign"],
        ["Produced", "Mood video for social media"]
      ],
      "c": "Moët & Chandon",
      "yt": "https://youtu.be/xefuBOJzwKU",
      "gl": "wide",
      "g": ["2", "3", "4", "5", "6", "7", "8", "9"],
      "lk": []
    },
    {
      "id": "monkeypopup",
      "s": "b",
      "b": "Monkey Shoulder",
      "t": "Pop-up shop: Hammock's Tropical Palace",
      "d": "Brand activation",
      "y": "2019",
      "r": "Brand activation management and creative strategy",
      "o": "",
      "role": [],
      "c": "Hammock Magazine",
      "yt": ["https://youtu.be/0BvSPy8cf6k", "https://youtu.be/QPxStHZZY6U"],
      "gl": "natural",
      "g": ["3", "7", "2", "5", "4", "6"],
      "lk": []
    }
  ],
  "SP": [
    { "id": "hennessy", "n": "Hennessy", "y": "2022", "d": "NBA campaign: social media content strategy", "u": "https://" },
    { "id": "visa", "n": "VISA", "y": "2022", "d": "Content strategy and creative direction for Instagram", "u": "https://" },
    { "id": "bmw", "n": "BMW", "y": "2024", "d": "Content strategy for BMW Experience", "u": "https://",
      "hl": [
        { "id": "bmwexp", "t": "BMW Experience", "u": "https://www.instagram.com/s/aGlnaGxpZ2h0OjE4MDY4NjY4ODY0OTc1ODcx?story_media_id=3726033781165934727", "f": [] }
      ] },
    { "id": "monkeyshoulder", "n": "Monkey Shoulder", "y": "2022", "d": "Instagram campaign concept and content calendar", "u": "https://",
      "hl": [
        { "id": "monkey1", "t": "Monkey Shoulder", "u": "https://www.instagram.com/s/aGlnaGxpZ2h0OjE4MTAxMDE3Mzg0MzA1MDM3?story_media_id=2790831856510126501", "f": [] }
      ] },
    { "id": "berlinale", "n": "Berlinale", "y": "", "d": "Instagram stories", "u": "https://",
      "hl": [
        { "id": "berlinale1", "t": "Berlinale", "u": "https://www.instagram.com/s/aGlnaGxpZ2h0OjE4MDY5ODAxMjM1NDgxNDY5?story_media_id=3309109697287613886", "f": [] }
      ] },
    { "id": "tbc", "n": "TBC", "y": "", "d": "Instagram content", "u": "https://" }
  ],
  "IG": [
    ["Reel", "Hennessy x NBA", "Social media content strategy", "hennessy1", "https://www.instagram.com/reel/CjnvuZDoAI5/", "hennessy"],
    ["Reel", "VISA", "Content strategy, creative direction", "visa1", "https://www.instagram.com/reel/CjsSPuqIMLe/", "visa"],
    ["Reel", "VISA", "Content strategy, creative direction", "visa2", "https://www.instagram.com/reel/Cj9-ikPj04w/", "visa"],
    ["Reel", "BMW Experience", "Content strategy", "bmw1", "https://www.instagram.com/reel/C8U2yV3IPYn/", "bmw"],
    ["Reel", "BMW Experience", "Content strategy", "bmw2", "https://www.instagram.com/reel/C8SeusfoqU8/", "bmw"],
    ["Reel", "Monkey Shoulder", "Campaign concept, content calendar", "monkey1", "https://www.instagram.com/reel/Cb2yWfOo9fw/", "monkeyshoulder"],
    ["Reel", "Monkey Shoulder", "Campaign concept, content calendar", "monkey2", "https://www.instagram.com/reel/CcImq5gIgA6/", "monkeyshoulder"],
    ["Reel", "Monkey Shoulder", "Campaign concept, content calendar", "monkey3", "https://www.instagram.com/reel/Ccao8QaoDZG/", "monkeyshoulder"],
    ["Reel", "Monkey Shoulder", "Campaign concept, content calendar", "monkey4", "https://www.instagram.com/reel/CcsrUy2Ien_/", "monkeyshoulder"],
    ["Reel", "TBC", "", "tbc1", "https://www.instagram.com/reel/C5F89SOIg1f/", "tbc"],
    ["Reel", "TBC", "", "tbc2", "https://www.instagram.com/reel/ChNVKKyIV-A/", "tbc"],
    ["Reel", "TBC", "", "tbc3", "https://www.instagram.com/reel/CcAYrcYoEXD/", "tbc"],
    ["Post", "TBC", "", "tbc4", "https://www.instagram.com/p/B_kXMsVhQvd/", "tbc"]
  ],
  "PP": [
    {
      "id": "dialoguenpause",
      "h": "Dialogue en Pause",
      "m": "A platform for stories where art and fashion meet. Ongoing.",
      "t": "I have always been fascinated by the dialogue between art and fashion—the ways in which the two disciplines intersect, influence, and reinterpret one another.\n\nDriven by this interest, I recently created Dialogue en Pause, a platform dedicated to telling stories of artistic and fashion interventions. It explores the moments where art enters into conversation with fashion, creating new narratives, perspectives, and forms of expression.\n\nThe name Dialogue en Pause is inspired by Gabrielle Chanel’s house, La Pausa—a place associated with creativity, encounters, and the meeting of art and fashion. Drawing from this spirit, the platform offers a space to pause, look closer, and explore the evolving dialogue between these two worlds.\n\nAs a content manager and storyteller, I believe the present—and the future—lies in niche, intimate forms of storytelling. In a world saturated with content, the most meaningful stories are often found in the details: a personal perspective, a handwritten note, a still image, a moving frame, or a conversation.\n\nDialogue en Pause is a platform created to explore these different languages of storytelling through the dialogue between art and fashion. It is a space where stories can take shape through handwriting, photography, film, interviews, animation, archival material, and other forms of visual and editorial expression.\n\nRather than following a single editorial format, Dialogue en Pause embraces experimentation. It is a living space for stories, ideas, and perspectives that sit between art and fashion—small, distinctive narratives that invite the audience to slow down and look closer.",
      "hd": "@dialoguenpause",
      "iu": "https://www.instagram.com/dialoguenpause/",
      "lk": [
        { "id": "dep1", "t": "", "u": "https://www.instagram.com/p/Dd-a4fZiHTf/" },
        { "id": "dep2", "t": "", "u": "https://www.instagram.com/p/DeKaNkQDr1t/" },
        { "id": "dep3", "t": "", "u": "https://www.instagram.com/p/DeBAsyOgjeW/" },
        { "id": "dep4", "t": "", "u": "https://www.instagram.com/p/DeAG1xbjmpl/" },
        { "id": "dep5", "t": "", "u": "https://www.instagram.com/p/DeLG22NAsXX/" },
        { "id": "dep6", "t": "", "u": "https://www.instagram.com/reel/DeLD2nLC-ZG/" }
      ]
    }
  ],
  "M": {
    "prvisah": { "u": "images/visa/visa-01.jpg", "t": "i" },
    "prvisa2": { "u": "images/visa/visa-02.jpg", "t": "i" },
    "prvisa3": { "u": "images/visa/visa-03.jpg", "t": "i" },
    "prvisa4": { "u": "images/visa/visa-04.jpg", "t": "i", "wide": true },
    "prvisa5": { "u": "images/visa/visa-05.jpg", "t": "i" },
    "prvisa6": { "u": "images/visa/visa-06.jpg", "t": "i" },
    "prvisa7": { "u": "images/visa/visa-07.jpg", "t": "i", "wide": true },
    "prvisa8": { "u": "images/visa/visa-08.jpg", "t": "i" },
    "prvisa9": { "u": "images/visa/visa-09.jpg", "t": "i" },
    "prafflelou1": { "u": "images/afflelou/afflelou-01.jpg", "t": "i" },
    "prafflelou2": { "u": "images/afflelou/afflelou-02.jpg", "t": "i" },
    "prafflelou3": { "u": "images/afflelou/afflelou-03.jpg", "t": "i" },
    "prafflelou4": { "u": "images/afflelou/afflelou-04.jpg", "t": "i" },
    "prtommyjeansh": { "u": "images/tommyjeans/tommyjeans-02.jpg", "t": "i" },
    "prtommyjeans1": { "u": "images/tommyjeans/tommyjeans-01.jpg", "t": "i", "wide": true },
    "prthebodyshoph": { "u": "images/thebodyshop/thebodyshop-02.jpg", "t": "i" },
    "prthebodyshop1": { "u": "images/thebodyshop/thebodyshop-01.jpg", "t": "i" },
    "prerborianh": { "u": "images/erborian/erborian-01.jpg", "t": "i" },
    "prerborian2": { "u": "images/erborian/erborian-02.jpg", "t": "i" },
    "prerborian3": { "u": "images/erborian/erborian-03.jpg", "t": "i" },
    "prerborian4": { "u": "images/erborian/erborian-04.jpg", "t": "i" },
    "prerborian5": { "u": "images/erborian/erborian-05.jpg", "t": "i" },
    "prerborian6": { "u": "images/erborian/erborian-06.jpg", "t": "i" },
    "prerborian7": { "u": "images/erborian/erborian-07.jpg", "t": "i" },
    "prerborian8": { "u": "images/erborian/erborian-08.jpg", "t": "i" },
    "prerborian9": { "u": "images/erborian/erborian-09.jpg", "t": "i" },
    "prmelvitah": { "u": "images/melvita/melvita-02.jpg", "t": "i" },
    "prmelvita1": { "u": "images/melvita/melvita-01.jpg", "t": "i" },
    "prmelvita3": { "u": "images/melvita/melvita-03.jpg", "t": "i" },
    "prmelvita4": { "u": "images/melvita/melvita-04.jpg", "t": "i", "wide": true },
    "prmelvita5": { "u": "images/melvita/melvita-05.jpg", "t": "i" },
    "prmelvita6": { "u": "images/melvita/melvita-06.jpg", "t": "i" },
    "prmonkeypopuph": { "u": "images/monkeyshoulder-popup/popup-01.jpg", "t": "i" },
    "prmonkeypopup2": { "u": "images/monkeyshoulder-popup/popup-02.jpg", "t": "i" },
    "prmonkeypopup3": { "u": "images/monkeyshoulder-popup/popup-03.jpg", "t": "i" },
    "prmonkeypopup4": { "u": "images/monkeyshoulder-popup/popup-04.jpg", "t": "i" },
    "prmonkeypopup5": { "u": "images/monkeyshoulder-popup/popup-05.jpg", "t": "i" },
    "prmonkeypopup6": { "u": "images/monkeyshoulder-popup/popup-06.jpg", "t": "i" },
    "prmonkeypopup7": { "u": "images/monkeyshoulder-popup/popup-07.jpg", "t": "i" },
    "prminih": { "u": "images/mini/mini-06.jpg", "t": "i" },
    "prmini1": { "u": "images/mini/mini-01.jpg", "t": "i" },
    "prmini2": { "u": "images/mini/mini-02.jpg", "t": "i" },
    "prmini3": { "u": "images/mini/mini-03.jpg", "t": "i" },
    "prmini4": { "u": "images/mini/mini-04.jpg", "t": "i" },
    "prmini5": { "u": "images/mini/mini-05.jpg", "t": "i" },
    "prmini7": { "u": "images/mini/mini-07.jpg", "t": "i", "wide": true },
    "prmini8": { "u": "images/mini/mini-08.jpg", "t": "i", "wide": true },
    "prmini9": { "u": "images/mini/mini-09.jpg", "t": "i", "wide": true },
    "prmini10": { "u": "images/mini/mini-10.jpg", "t": "i" },
    "prmini11": { "u": "images/mini/mini-11.jpg", "t": "i" },
    "prmini12": { "u": "images/mini/mini-12.jpg", "t": "i" },
    // CV link on the About and Contact pages. Upload your CV to the repo as cv.pdf.
    "cv": { "u": "cv.pdf", "t": "f" },
    "hlcberlinale1": { "u": "images/berlinale/berlinale-logo.jpg", "t": "i" },
    "hlcmonkey1": { "u": "images/monkeyshoulder/monkeyshoulder-logo.jpg", "t": "i" },
    "hlcbmwexp": { "u": "images/bmw/bmw-logo.svg", "t": "i" },
    "about": { "u": "images/me/portrait.jpg", "t": "i" },
    "prmoeth": { "u": "images/moet/moet-01.jpg", "t": "i" },
    "prmoet2": { "u": "images/moet/moet-02.jpg", "t": "i" },
    "prmoet3": { "u": "images/moet/moet-03.jpg", "t": "i" },
    "prmoet4": { "u": "images/moet/moet-04.jpg", "t": "i" },
    "prmoet5": { "u": "images/moet/moet-05.jpg", "t": "i" },
    "prmoet6": { "u": "images/moet/moet-06.jpg", "t": "i" },
    "prmoet7": { "u": "images/moet/moet-07.jpg", "t": "i" },
    "prmoet8": { "u": "images/moet/moet-08.jpg", "t": "i" },
    "prmoet9": { "u": "images/moet/moet-09.jpg", "t": "i" }
  }
};
