// Site content. Anything set here overrides the defaults in index.html.
// Easiest way to change it: open index.html?edit in a browser, edit the page,
// click "Download content.js", and replace this file with the downloaded one.
window.SITE = {
  // Home page "What I do" boxes
  "sides": {"c": {"h": "Content & editorial strategy", "p": "The thinking: what gets made, for whom, and in what voice.", "li": ["Strategy for launches, campaigns and brand moments", "Narratives, content pillars and tone of voice", "Editorial planning, writing and editing", "Web, print and social: Instagram, TikTok, creator-led formats"]}, "p": {"h": "Creative direction & production", "p": "The making: concepts, visuals and the team that brings them to life.", "li": ["Concepts and visual direction for campaigns", "End-to-end production, from brief to rollout", "Leading a team of 10 across content, social, film and styling", "Clients, agencies, influencers and partners"]}},
  // About Me page
  "ABOUT": {
    "h": "Head of Content & Creative Strategy",
    "sub": "Hammock Magazine & Studio Agency · 5 years",
    "sec": [
      {
        "h": "Social-First Brand & Content Strategy",
        "t": "Led content strategies for launches, campaigns and key brand moments, translating brand identity into clear narratives, content pillars and tone of voice across web, print and social platforms, including Instagram, TikTok and creator-led formats."
      },
      {
        "h": "Editorial Leadership & Storytelling",
        "t": "Led editorial planning and wrote, edited and managed content across web, print and social media. Drew on a background in journalism and inspiration from art, culture and society to shape narratives that combine editorial rigor with creativity."
      },
      {
        "h": "Creative Direction & Digital Brand Image",
        "t": "Developed concepts and visual directions across campaign assets, short-form content and always-on storytelling, ensuring platform relevance and a distinctive, consistent brand expression."
      },
      {
        "h": "Production & Cross-Functional Delivery",
        "t": "Led end-to-end content production, from brief and concept through post-production and delivery. Partnered with clients, contributors, influencers and external partners, translating complex briefs into clear, impactful, audience-focused content."
      },
      {
        "h": "Team Management",
        "t": "Managed and mentored a team of 10, including permanent staff (content managers, social media managers, editors, directors and camera operators) and freelance creative producers, stylists and makeup artists. Oversaw priorities, workflows and creative quality across content development and delivery."
      },
      {
        "h": "Performance & Optimization",
        "t": "Ensured content performance and visibility across digital platforms through SEO and GEO practices, supporting broader brand and corporate communication objectives."
      }
    ]
  },
  "title": "Head of Content & Creative Strategy",
  // Menu order
  "NAV": ["work", "social", "personal", "articles", "about"],
  // Menu and page titles
  "T": { "n1": "Projects", "n2": "Social Media", "n3": "Personal Project", "n4": "About Me", "w1": "Projects", "s1": "Social Media", "p0": "Personal Project", "n6": "Writing & Editorial", "ar1": "Writing & Editorial", "h7": "Writing & Editorial", "ar2": "Editorial stories on art, fashion, photography, cinema and architecture.", "f1": "Head of Content & Creative Strategy", "h1": "What I do", "h3": "Social Media", "h4": "All social media" },
  // Social Media projects shown on the home page
  "HOMEIG": ["hennessy", "lamborghini", "visa"],
  "L": { "email": "Chanadirigvanca@gmail.com", "li": "https://www.linkedin.com/in/your-profile", "ig": "https://instagram.com/your-handle" },
  // Order of the Work list. "p" = Work project id, "s" = Social Media project id.
  // Writing & Editorial filter categories
  "CAT": [{"id":"art","n":"Art"},{"id":"fashion","n":"Fashion"},{"id":"photography","n":"Photography"},{"id":"cinema","n":"Cinema"},{"id":"architecture","n":"Architecture"},{"id":"interviews","n":"Interviews"}],
  // Writing & Editorial pieces
  // Editorial Features: headline + photo grid
  "EF": [{"id":"sarajishvili","h":"Project Sarajishvili","imgs":["images/sarajishvili/sarajishvili-01.jpg","images/sarajishvili/sarajishvili-02.jpg","images/sarajishvili/sarajishvili-03.jpg","images/sarajishvili/sarajishvili-04.jpg","images/sarajishvili/sarajishvili-05.jpg","images/sarajishvili/sarajishvili-06.jpg"]},{"id":"idealtd","h":"Interview with IDEA.LTD","imgs":["images/idealtd/idealtd-01.jpg","images/idealtd/idealtd-02.jpg","images/idealtd/idealtd-03.jpg","images/idealtd/idealtd-04.jpg","images/idealtd/idealtd-05.jpg","images/idealtd/idealtd-06.jpg"],"pos":["85% center","center","center 40%","center","center 65%","center"]},{"id":"keburia","h":"KEBURIA SS2022","imgs":["images/keburia/keburia-01.jpg","images/keburia/keburia-02.jpg","images/keburia/keburia-03.jpg","images/keburia/keburia-04.jpg","images/keburia/keburia-05.jpg"],"pos":["58% center","center 25%","center 60%","center 75%","center 50%"]},{"id":"fashioned","h":"Project 1 INSTEAD OF 100","imgs":["images/fashion-editorial/fashion-01.jpg","images/fashion-editorial/fashion-02.jpg","images/fashion-editorial/fashion-03.jpg","images/fashion-editorial/fashion-04.jpg","images/fashion-editorial/fashion-05.jpg","images/fashion-editorial/fashion-06.jpg"],"pos":["48% center","center 35%","center 55%","center 30%","60% center","center 40%"]},{"id":"situationist","h":"SITUATIONIST","imgs":["images/situationist/situationist-01.jpg","images/situationist/situationist-02.jpg","images/situationist/situationist-03.jpg","images/situationist/situationist-04.jpg","images/situationist/situationist-05.jpg","images/situationist/situationist-06.jpg","images/situationist/situationist-07.jpg"],"pos":["center","center 40%","48% center","center 60%","center","center 55%","center 55%"]},{"id":"artists","h":"Interviews with Artists","sets":[{"imgs":["images/artists/artists-01.jpg","images/artists/artists-02.jpg","images/artists/artists-03.jpg","images/artists/artists-04.jpg","images/artists/artists-20.jpg"],"pos":["center","center","center","center","center"]},{"imgs":["images/artists/artists-05.jpg","images/artists/artists-06.jpg","images/artists/artists-07.jpg","images/artists/artists-08.jpg","images/artists/artists-19.jpg"],"pos":["50% 40%","center","center 50%","62% center","center 45%"]},{"imgs":["images/artists/artists-09.jpg","images/artists/artists-10.jpg","images/artists/artists-11.jpg","images/artists/artists-12.jpg","images/artists/artists-13.jpg"],"pos":["center 35%","center","center 30%","center 45%","52% center"]},{"imgs":["images/field/field-01.jpg","images/field/field-02.jpg","images/field/field-03.jpg","images/field/field-04.jpg","images/field/field-05.jpg"],"pos":["center","center 40%","center 65%","40% center","center 45%"]},{"imgs":["images/artists/artists-14.jpg","images/artists/artists-15.jpg","images/artists/artists-16.jpg","images/artists/artists-17.jpg","images/artists/artists-18.jpg"],"pos":["42% center","center 40%","center 45%","center","62% center"]}]}],
  "A": [
    { "id": "ed1", "t": "", "pub": "", "dt": "", "cat": "art", "u": "https://www.instagram.com/p/C_cv55jI2_Y/" },
    { "id": "ed2", "t": "", "pub": "", "dt": "", "cat": "fashion", "u": "https://www.instagram.com/p/C_S-_jjIw8q/" },
    { "id": "ed3", "t": "", "pub": "", "dt": "", "cat": "photography", "u": "https://www.instagram.com/p/C_P36KuMORN/" },
    { "id": "ed4", "t": "", "pub": "", "dt": "", "cat": "photography", "u": "https://www.instagram.com/p/C-2H3ggoke-/" },
    { "id": "ed5", "t": "", "pub": "", "dt": "", "cat": "photography", "u": "https://www.instagram.com/p/C9ZpIYjIg_D/" },
    { "id": "ed6", "t": "", "pub": "", "dt": "", "cat": "cinema", "u": "https://www.instagram.com/p/C14LHpJoVzF/" },
    { "id": "ed7", "t": "", "pub": "", "dt": "", "cat": "fashion", "u": "https://www.instagram.com/p/Cx3SvpXI-kd/" },
    { "id": "ed8", "t": "", "pub": "", "dt": "", "cat": "art", "u": "https://www.instagram.com/p/CwhTH1HIVCl/" },
    { "id": "ed9", "t": "", "pub": "", "dt": "", "cat": "architecture", "u": "https://www.instagram.com/p/CwMoGAHo1Cm/" },
    { "id": "ed10", "t": "", "pub": "", "dt": "", "cat": "architecture", "u": "https://www.instagram.com/p/CwFUczUoF4I/" },
    { "id": "ed11", "t": "", "pub": "", "dt": "", "cat": "cinema", "u": "https://www.instagram.com/p/Cv9TmjxIguX/" },
    { "id": "ed12", "t": "", "pub": "", "dt": "", "cat": "architecture", "u": "https://www.instagram.com/p/Cv7e9QkI1UF/" },
    { "id": "ed13", "t": "", "pub": "", "dt": "", "cat": "fashion", "u": "https://www.instagram.com/p/Cm_9kIzIJG-/" },
    { "id": "ed14", "t": "", "pub": "", "dt": "", "cat": "cinema", "u": "https://www.instagram.com/p/CmMPXygoVF-/" },
    { "id": "ed15", "t": "", "pub": "", "dt": "", "cat": "cinema", "u": "https://www.instagram.com/p/ChwVtVuIUk_/" },
    { "id": "ed16", "t": "", "pub": "", "dt": "", "cat": "art", "u": "https://www.instagram.com/p/CgomP0lIVN1/" },
    { "id": "ed17", "t": "", "pub": "", "dt": "", "cat": "art", "u": "https://www.instagram.com/p/Cf6ozBSoW2m/" },
    { "id": "ed18", "t": "", "pub": "", "dt": "", "cat": "photography", "u": "https://www.instagram.com/p/CcC3zSWoN2B/" },
    { "id": "ed19", "t": "", "pub": "", "dt": "", "cat": "cinema", "u": "https://www.instagram.com/p/CYdzXgQIkTq/" },
    { "id": "ed20", "t": "", "pub": "", "dt": "", "cat": "cinema", "u": "https://www.instagram.com/p/CYWNGtwoxYy/" },
    { "id": "ed21", "t": "", "pub": "", "dt": "", "cat": "art", "u": "https://www.instagram.com/p/CXx6RoRI0mr/" },
    { "id": "ed22", "t": "", "pub": "", "dt": "", "cat": "cinema", "u": "https://www.instagram.com/p/CWD1a8HIiwP/" },
    { "id": "ed23", "t": "", "pub": "", "dt": "", "cat": "fashion", "u": "https://www.instagram.com/p/CUsTMyiodgf/" },
    { "id": "ed24", "t": "", "pub": "", "dt": "", "cat": "cinema", "u": "https://www.instagram.com/p/CUPlgiAI_sw/" },
    { "id": "ed25", "t": "", "pub": "", "dt": "", "cat": "art", "u": "https://www.instagram.com/p/CTwkjc5ouuX/" },
    { "id": "ed26", "t": "", "pub": "", "dt": "", "cat": "photography", "u": "https://www.instagram.com/p/CTuO9V-IQN8/" },
    { "id": "ed27", "t": "", "pub": "", "dt": "", "cat": "fashion", "u": "https://www.instagram.com/p/CTmAE2qoXKF/" },
    { "id": "ed28", "t": "", "pub": "", "dt": "", "cat": "cinema", "u": "https://www.instagram.com/p/CTSC_ftoDHT/" },
    { "id": "ed29", "t": "", "pub": "", "dt": "", "cat": "art", "u": "https://www.instagram.com/p/CTE1qKVoKCK/" },
    { "id": "ed30", "t": "", "pub": "", "dt": "", "cat": "photography", "u": "https://www.instagram.com/p/CSjFJ_VIJNe/" },
    { "id": "ed31", "t": "", "pub": "", "dt": "", "cat": "fashion", "u": "https://www.instagram.com/p/CQyEZJcLrCc/" },
    { "id": "ed32", "t": "", "pub": "", "dt": "", "cat": "fashion", "u": "https://www.instagram.com/p/CO0dq2oh9hg/" },
    { "id": "ed33", "t": "", "pub": "", "dt": "", "cat": "art", "u": "https://www.instagram.com/p/COcpyjdBv28/" },
    { "id": "ed34", "t": "", "pub": "", "dt": "", "cat": "art", "u": "https://www.instagram.com/p/CNkvSLPho4M/" },
    { "id": "ed35", "t": "", "pub": "", "dt": "", "cat": "fashion", "u": "https://www.instagram.com/p/CNZyfOuBnhy/" },
    { "id": "ed36", "t": "", "pub": "", "dt": "", "cat": "cinema", "u": "https://www.instagram.com/p/CMw41O0BFGn/" },
    { "id": "ed37", "t": "", "pub": "", "dt": "", "cat": "photography", "u": "https://www.instagram.com/p/CM1yAUrhyue/" },
    { "id": "ed38", "t": "", "pub": "", "dt": "", "cat": "art", "u": "https://www.instagram.com/p/CLeUTgWB7NX/" },
    { "id": "ed39", "t": "", "pub": "", "dt": "", "cat": "art", "u": "https://www.instagram.com/p/CK1WQprhDyA/" },
    { "id": "ed40", "t": "", "pub": "", "dt": "", "cat": "cinema", "u": "https://www.instagram.com/p/CKoZ89rBgfE/" },
    { "id": "ed41", "t": "", "pub": "", "dt": "", "cat": "photography", "u": "https://www.instagram.com/p/CKl4PKKh2-F/" },
    { "id": "ed42", "t": "", "pub": "", "dt": "", "cat": "cinema", "u": "https://www.instagram.com/p/CKWY0FxBhlL/" },
    { "id": "ed43", "t": "", "pub": "", "dt": "", "cat": "cinema", "u": "https://www.instagram.com/p/CJnp5hkBuSi/" },
    { "id": "ed44", "t": "", "pub": "", "dt": "", "cat": "cinema", "u": "https://www.instagram.com/p/CGpuWBShL3A/" },
    { "id": "ed45", "t": "", "pub": "", "dt": "", "cat": "art", "u": "https://www.instagram.com/p/CFmHY--BetO/" },
    { "id": "ed46", "t": "", "pub": "", "dt": "", "cat": "cinema", "u": "https://www.instagram.com/p/CD36yFrBSy5/" },
    { "id": "ed47", "t": "", "pub": "", "dt": "", "cat": "fashion", "u": "https://www.instagram.com/p/CDWgfYoBqFs/" },
    { "id": "ed48", "t": "", "pub": "", "dt": "", "cat": "photography", "u": "https://www.instagram.com/p/C-u1FvrIHvt/" },
    { "id": "ed49", "t": "", "pub": "", "dt": "", "cat": "cinema", "u": "https://www.instagram.com/p/C9hx9-0orWE/" },
    { "id": "ed50", "t": "", "pub": "", "dt": "", "cat": "art", "u": "https://www.instagram.com/p/C8WXXnaIVvF/" },
    { "id": "ed51", "t": "", "pub": "", "dt": "", "cat": "fashion", "u": "https://www.instagram.com/p/C2Cbj6dIW48/" },
    { "id": "ed52", "t": "", "pub": "", "dt": "", "cat": "fashion", "u": "https://www.instagram.com/p/CxsKfL4I_rD/" },
    { "id": "ed53", "t": "", "pub": "", "dt": "", "cat": "cinema", "u": "https://www.instagram.com/p/Cw2Tn7so2WX/" }
  ],
  "ORDER": [
    {"p": "moet", "s": "moet"},
    {"s": "hennessy"},
    {"p": "monkeypopup", "s": "monkeyshoulder"},
    {"p": "erborian"},
    {"p": "melvita"},
    {"p": "thebodyshop"},
    {"p": "tommyjeans"},
    {"p": "afflelou"},
    {"p": "visa", "s": "visa"},
    {"p": "porsche"},
    {"s": "lamborghini"},
    {"p": "mini"},
    {"s": "bmw"},
    {"s": "volvo"},
    {"p": "wissol"},
    {"s": "tbc"},
    {"p": "venicebiennale"},
    {"p": "venicearchitecture"},
    {"p": "milandesignweek"},
    {"s": "mbfw"},
    {"s": "berlinale"}
  ],
  "name": "Gvantsa Chanadiri",
  "bw": false,
  "P": [
    {
      "id": "wissol",
      "s": "c",
      "b": "Wissol Group",
      "t": "Campaign content",
      "d": "Photo",
      "y": "",
      "r": "",
      "o": "",
      "role": [],
      "c": "",
      "gl": "natural",
      "g": ["1", "2", "3", "5", "6"],
      "lk": [
        { "id": "wissol1", "ty": "Instagram post", "t": "Wissol Group video", "s": "Instagram", "u": "https://www.instagram.com/tv/CfrSMdiFReQ/" },
        { "id": "wissol2", "ty": "Instagram post", "t": "Wissol Group post", "s": "Instagram", "u": "https://www.instagram.com/p/Cf1LojBIuPO/" }
      ]
    },
    {
      "id": "milandesignweek",
      "s": "c",
      "b": "Milan Design Week",
      "t": "Social media content",
      "d": "Social",
      "y": "",
      "r": "",
      "o": "",
      "role": [],
      "c": "",
      "g": [],
      "lk": [
        { "id": "milan1", "ty": "Instagram post", "t": "Milan Design Week reel", "s": "Instagram", "u": "https://www.instagram.com/reel/C58OXMvoega/" },
        { "id": "milan2", "ty": "Instagram post", "t": "Milan Design Week reel", "s": "Instagram", "u": "https://www.instagram.com/reel/C56TZCzI_BT/" },
        { "id": "milan3", "ty": "Instagram post", "t": "Milan Design Week reel", "s": "Instagram", "u": "https://www.instagram.com/reel/C56Kv0gorrZ/" },
        { "id": "milan4", "ty": "Instagram post", "t": "Milan Design Week reel", "s": "Instagram", "u": "https://www.instagram.com/reel/C50VfVmoutL/" },
        { "id": "milan5", "ty": "Instagram post", "t": "Milan Design Week reel", "s": "Instagram", "u": "https://www.instagram.com/reel/C51I6dvoTwb/" }
      ]
    },
    {
      "id": "venicearchitecture",
      "s": "c",
      "b": "Venice Architecture Biennale",
      "t": "Social media content",
      "d": "Social",
      "y": "",
      "r": "",
      "o": "",
      "role": [],
      "c": "",
      "yt": ["https://youtu.be/ndRkjAUeWMk"],
      "g": [],
      "lk": [
        { "id": "venicearch1", "ty": "Instagram post", "t": "Venice Architecture Biennale post", "s": "Instagram", "u": "https://www.instagram.com/p/DJbkEycCf6T/" }
      ]
    },
    {
      "id": "venicebiennale",
      "s": "c",
      "b": "Venice Art Biennale",
      "t": "Video content",
      "d": "Video",
      "y": "",
      "r": "",
      "o": "",
      "role": [],
      "c": "",
      "yt": ["https://youtu.be/75sjBFTLekc", "https://youtu.be/btKha_pmXCw", "https://youtu.be/6Cv28_LKl4E"],
      "g": [],
      "lk": [
        { "id": "venice1", "ty": "Instagram post", "t": "Venice Art Biennale reel", "s": "Instagram", "u": "https://www.instagram.com/reel/CsdsF6zI0PM/" },
        { "id": "venice2", "ty": "Instagram post", "t": "Venice Art Biennale reel", "s": "Instagram", "u": "https://www.instagram.com/reel/Csgl-MwoxVa/" },
        { "id": "venice3", "ty": "Instagram post", "t": "Venice Art Biennale reel", "s": "Instagram", "u": "https://www.instagram.com/reel/Csiv4eGIcxA/" },
        { "id": "venice4", "ty": "Instagram post", "t": "Venice Art Biennale reel", "s": "Instagram", "u": "https://www.instagram.com/reel/Cs3CIaTom_T/" },
        { "id": "venice5", "ty": "Instagram post", "t": "Venice Art Biennale reel", "s": "Instagram", "u": "https://www.instagram.com/reel/Cc29J9toID0/" },
        { "id": "venice6", "ty": "Instagram post", "t": "Venice Art Biennale reel", "s": "Instagram", "u": "https://www.instagram.com/reel/Cc0fCiFIBv7/" },
        { "id": "venice7", "ty": "Instagram post", "t": "Venice Art Biennale reel", "s": "Instagram", "u": "https://www.instagram.com/reel/Ccnxw7NI150/" },
        { "id": "venice8", "ty": "Instagram post", "t": "Venice Art Biennale reel", "s": "Instagram", "u": "https://www.instagram.com/reel/C6Enf7coCw2/" }
      ]
    },
    {
      "id": "afflelou",
      "s": "c",
      "b": "Afflelou Paris",
      "t": "Eyewear campaign",
      "d": "Photo",
      "y": "",
      "r": "",
      "o": "",
      "role": [],
      "c": "",
      "gl": "natural",
      "g": ["1", "2", "3", "4"],
      "lk": [
        { "id": "afflelou1", "ty": "Instagram post", "t": "Afflelou Paris reel", "s": "Instagram", "u": "https://www.instagram.com/reel/CylVX6ML7uK/" },
        { "id": "afflelou2", "ty": "Instagram post", "t": "Afflelou Paris reel", "s": "Instagram", "u": "https://www.instagram.com/reel/CfUJIbBomjg/" }
      ]
    },
    {
      "id": "tommyjeans",
      "s": "b",
      "b": "Tommy Jeans",
      "t": "Campaign content",
      "d": "Photo",
      "y": "",
      "r": "Content strategy and production",
      "o": "",
      "role": [],
      "c": "",
      "gl": "natural",
      "g": ["1"],
      "lk": [
        { "id": "tommyjeans1", "ty": "Instagram post", "t": "Tommy Jeans reel", "s": "Instagram", "u": "https://www.instagram.com/reel/C3Ac39wo3u3/" },
        { "id": "tommyjeans2", "ty": "Instagram post", "t": "Tommy Jeans post", "s": "Instagram", "u": "https://www.instagram.com/p/CnwB28HoOuM/" }
      ]
    },
    {
      "id": "thebodyshop",
      "s": "c",
      "b": "The Body Shop",
      "t": "Video content",
      "d": "Video",
      "y": "",
      "r": "",
      "o": "",
      "role": [],
      "c": "",
      "yt": ["https://youtu.be/bkxummNJVuk", "https://youtu.be/rz-E1WPiv0k", "https://youtu.be/03DNWpoFP8E", "https://youtu.be/4K6jf9dU_U8", "https://youtu.be/n7d7bv15p1Q"],
      "gl": "natural",
      "g": ["1"],
      "lk": []
    },
    {
      "id": "melvita",
      "s": "c",
      "b": "Melvita",
      "t": "Editorial and social media content",
      "d": "Social",
      "y": "2024",
      "r": "Content strategy, editorial and social media content",
      "o": "",
      "role": [],
      "c": "",
      "gl": "natural",
      "g": ["1", "3", "4", "5", "6"],
      "lk": [
        { "id": "melvita1", "ty": "Instagram post", "t": "Melvita reel", "s": "Instagram", "u": "https://www.instagram.com/reel/DK9L8dAtDOD/" },
        { "id": "melvita2", "ty": "Instagram post", "t": "Melvita reel", "s": "Instagram", "u": "https://www.instagram.com/reel/DK_wCg1MHO8/" },
        { "id": "melvita3", "ty": "Instagram post", "t": "Melvita reel", "s": "Instagram", "u": "https://www.instagram.com/reel/DLPMv4iNRjO/" }
      ]
    },
    {
      "id": "erborian",
      "s": "p",
      "b": "Erborian",
      "t": "Beauty campaign",
      "d": "Photo",
      "y": "2024",
      "r": "Creative strategy and production",
      "o": "",
      "role": [],
      "c": "",
      "gl": "natural",
      "g": ["2", "3", "4", "9", "5", "6", "7", "8"],
      "lk": [
        { "id": "erborian1", "ty": "Instagram post", "t": "Erborian reel", "s": "Instagram", "u": "https://www.instagram.com/reel/DRfRPI5ANMr/" }
      ]
    },
    {
      "id": "visa",
      "s": "c",
      "b": "Visa",
      "t": "Video content",
      "d": "Video",
      "y": "2024",
      "r": "Content strategy",
      "o": "",
      "role": [],
      "c": "",
      "yt": ["https://youtu.be/h6c97OslT94", "https://youtu.be/_u-0jIrRos8", "https://youtu.be/O0OU0cRffI0", "https://youtu.be/Dvzh21KFhaA"],
      "gl": "natural",
      "g": ["2", "3", "4", "5", "6", "7", "8", "9"],
      "lk": []
    },
    {
      "id": "mini",
      "s": "b",
      "b": "MINI",
      "t": "Campaign and editorial photography",
      "d": "Photo",
      "y": "2024",
      "r": "Content management and creative production",
      "o": "",
      "role": [],
      "c": "Hammock Magazine",
      "gl": "natural",
      "g": ["1", "2", "3", "4", "7", "8", "5", "10", "11", "12", "9"],
      "lk": []
    },
    {
      "id": "porsche",
      "s": "c",
      "b": "Porsche",
      "t": "Video content",
      "d": "Video",
      "y": "2024",
      "r": "Content management",
      "o": "",
      "role": [],
      "c": "",
      "yt": "https://youtu.be/JdZNGuG9KFU",
      "g": [],
      "lk": []
    },
    {
      "id": "moet",
      "s": "p",
      "b": "Moët & Chandon",
      "t": "Summer campaign: digital art and mood video",
      "d": "Digital art",
      "y": "2020",
      "r": "Campaign artwork, social content",
      "o": "Summer, told through illustrated Moët moments: city nights, rooftop picnics, beach days and celebrations. Nine digital artworks and a mood video for social media.",
      "role": [
        ["Produced", "Nine illustrated scenes for the summer campaign"],
        ["Produced", "Mood video for social media"]
      ],
      "c": "Moët & Chandon",
      "yt": "https://youtu.be/xefuBOJzwKU",
      "gl": "wide",
      "g": ["2", "3", "4", "5", "6", "7", "8", "9"],
      "lk": []
    },
    {
      "id": "monkeypopup",
      "s": "b",
      "b": "Monkey Shoulder",
      "t": "Pop-up shop: Hammock's Tropical Palace",
      "d": "Brand activation",
      "y": "2019",
      "r": "Brand activation management and creative strategy",
      "o": "",
      "role": [],
      "c": "Hammock Magazine",
      "yt": ["https://youtu.be/0BvSPy8cf6k", "https://youtu.be/QPxStHZZY6U"],
      "gl": "natural",
      "g": ["3", "7", "2", "5", "4", "6"],
      "lk": []
    }
  ],
  "SP": [
    { "id": "hennessy", "r": "Social media content strategy", "n": "Hennessy", "y": "2022", "d": "NBA campaign: social media content strategy", "u": "https://" },
    { "id": "visa", "r": "Content strategy and creative direction", "n": "Visa", "y": "2022", "d": "Content strategy and creative direction for Instagram", "u": "https://" },
    { "id": "bmw", "r": "Content strategy", "n": "BMW", "y": "2024", "d": "Content strategy for BMW Experience", "u": "https://",
      "hl": [
        { "id": "bmwexp", "t": "BMW Experience", "u": "https://www.instagram.com/s/aGlnaGxpZ2h0OjE4MDY4NjY4ODY0OTc1ODcx?story_media_id=3726033781165934727", "f": [] }
      ] },
    { "id": "monkeyshoulder", "r": "Instagram campaign concept and content calendar", "n": "Monkey Shoulder", "y": "2022", "d": "Instagram campaign concept and content calendar", "u": "https://",
      "hl": [
        { "id": "monkey1", "t": "Monkey Shoulder", "u": "https://www.instagram.com/s/aGlnaGxpZ2h0OjE4MTAxMDE3Mzg0MzA1MDM3?story_media_id=2790831856510126501", "f": [] }
      ] },
    { "id": "berlinale", "n": "Berlin Film Festival", "y": "", "d": "Instagram stories", "u": "https://",
      "hl": [
        { "id": "berlinale1", "t": "Berlin Film Festival", "u": "https://www.instagram.com/s/aGlnaGxpZ2h0OjE4MDY5ODAxMjM1NDgxNDY5?story_media_id=3309109697287613886", "f": [] }
      ] },
    { "id": "tbc", "n": "TBC", "y": "", "d": "Instagram content", "u": "https://" },
    { "id": "lamborghini", "n": "Lamborghini", "y": "", "d": "Instagram content", "u": "https://" },
    { "id": "mbfw", "n": "Mercedes-Benz Fashion Week", "y": "", "d": "Social media content", "u": "https://",
      "yt": ["https://youtu.be/2JqDN6lyRfo"],
      "pg": [{"h": "Backstage Photos", "imgs": ["images/mbfw/backstage-01.jpg","images/mbfw/backstage-02.jpg","images/mbfw/backstage-03.jpg","images/mbfw/backstage-04.jpg","images/mbfw/backstage-05.jpg","images/mbfw/backstage-06.jpg","images/mbfw/backstage-07.jpg","images/mbfw/backstage-08.jpg","images/mbfw/backstage-09.jpg","images/mbfw/backstage-10.jpg"], "pos": ["center 40%","center 35%","center 40%","center 40%","center 40%","center 25%","center 45%","center 40%","center 35%","30% center"]}],
      "links": [ { "t": "Watch on TikTok", "u": "https://vm.tiktok.com/ZN8kpnS74/" } ] },
    { "id": "moet", "n": "Moët & Chandon", "y": "", "d": "Instagram content", "u": "https://" },
    { "id": "volvo", "n": "Volvo", "y": "", "d": "Instagram content", "u": "https://" }
  ],
  "IG": [
    ["Reel", "Hennessy x NBA", "Social media content strategy", "hennessy1", "https://www.instagram.com/reel/CjnvuZDoAI5/", "hennessy"],
    ["Reel", "VISA", "Content strategy, creative direction", "visa1", "https://www.instagram.com/reel/CjsSPuqIMLe/", "visa"],
    ["Reel", "VISA", "Content strategy, creative direction", "visa2", "https://www.instagram.com/reel/Cj9-ikPj04w/", "visa"],
    ["Reel", "BMW Experience", "Content strategy", "bmw1", "https://www.instagram.com/reel/C8U2yV3IPYn/", "bmw"],
    ["Reel", "BMW Experience", "Content strategy", "bmw2", "https://www.instagram.com/reel/C8SeusfoqU8/", "bmw"],
    ["Reel", "Monkey Shoulder", "Campaign concept, content calendar", "monkey1", "https://www.instagram.com/reel/Cb2yWfOo9fw/", "monkeyshoulder"],
    ["Reel", "Monkey Shoulder", "Campaign concept, content calendar", "monkey2", "https://www.instagram.com/reel/CcImq5gIgA6/", "monkeyshoulder"],
    ["Reel", "Monkey Shoulder", "Campaign concept, content calendar", "monkey3", "https://www.instagram.com/reel/Ccao8QaoDZG/", "monkeyshoulder"],
    ["Reel", "Monkey Shoulder", "Campaign concept, content calendar", "monkey4", "https://www.instagram.com/reel/CcsrUy2Ien_/", "monkeyshoulder"],
    ["Reel", "TBC", "", "tbc1", "https://www.instagram.com/reel/C5F89SOIg1f/", "tbc"],
    ["Reel", "TBC", "", "tbc2", "https://www.instagram.com/reel/ChNVKKyIV-A/", "tbc"],
    ["Reel", "TBC", "", "tbc3", "https://www.instagram.com/reel/CcAYrcYoEXD/", "tbc"],
    ["Post", "TBC", "", "tbc4", "https://www.instagram.com/p/B_kXMsVhQvd/", "tbc"],
    ["Reel", "Lamborghini", "", "lambo1", "https://www.instagram.com/reel/DLIghs8tmoY/", "lamborghini"],
    ["Reel", "Mercedes-Benz Fashion Week", "", "mbfw1", "https://www.instagram.com/reel/C61JnV8oEMb/", "mbfw"],
    ["Reel", "Mercedes-Benz Fashion Week", "", "mbfw2", "https://www.instagram.com/reel/Cr3AZzYIuOB/", "mbfw"],
    ["Reel", "Volvo", "", "volvo1", "https://www.instagram.com/reel/DOzY6_bAtal/", "volvo"],
    ["Post", "Volvo", "", "volvo2", "https://www.instagram.com/p/DOzSQWPDM9x/", "volvo"],
    ["Reel", "Moët & Chandon", "", "moet1", "https://www.instagram.com/reel/Cgt0sSioW1i/", "moet"]
  ],
  "PP": [
    {
      "id": "dialoguenpause",
      "h": "Dialogue en Pause",
      "m": "A platform for stories where art and fashion meet. Ongoing.",
      "t": "I have always been fascinated by the dialogue between art and fashion—the ways in which the two disciplines intersect, influence, and reinterpret one another.\n\nDriven by this interest, I recently created Dialogue en Pause, a platform dedicated to telling stories of artistic and fashion interventions. It explores the moments where art enters into conversation with fashion, creating new narratives, perspectives, and forms of expression.\n\nThe name Dialogue en Pause is inspired by Gabrielle Chanel’s house, La Pausa—a place associated with creativity, encounters, and the meeting of art and fashion. Drawing from this spirit, the platform offers a space to pause, look closer, and explore the evolving dialogue between these two worlds.\n\nAs a content manager and storyteller, I believe the present—and the future—lies in niche, intimate forms of storytelling. In a world saturated with content, the most meaningful stories are often found in the details: a personal perspective, a handwritten note, a still image, a moving frame, or a conversation.\n\nDialogue en Pause is a platform created to explore these different languages of storytelling through the dialogue between art and fashion. It is a space where stories can take shape through handwriting, photography, film, interviews, animation, archival material, and other forms of visual and editorial expression.\n\nRather than following a single editorial format, Dialogue en Pause embraces experimentation. It is a living space for stories, ideas, and perspectives that sit between art and fashion—small, distinctive narratives that invite the audience to slow down and look closer.",
      "hd": "@dialoguenpause",
      "iu": "https://www.instagram.com/dialoguenpause/",
      "lk": [
        { "id": "dep1", "t": "", "u": "https://www.instagram.com/p/Dd-a4fZiHTf/" },
        { "id": "dep2", "t": "", "u": "https://www.instagram.com/p/DeKaNkQDr1t/" },
        { "id": "dep3", "t": "", "u": "https://www.instagram.com/p/DeBAsyOgjeW/" },
        { "id": "dep4", "t": "", "u": "https://www.instagram.com/p/DeAG1xbjmpl/" },
        { "id": "dep5", "t": "", "u": "https://www.instagram.com/p/DeLG22NAsXX/" },
        { "id": "dep6", "t": "", "u": "https://www.instagram.com/reel/DeLD2nLC-ZG/" }
      ]
    }
  ],
  "M": {
    "prwissolh": { "u": "images/wissol/wissol-04.jpg", "t": "i" },
    "prwissol1": { "u": "images/wissol/wissol-01.jpg", "t": "i" },
    "prwissol2": { "u": "images/wissol/wissol-02.jpg", "t": "i" },
    "prwissol3": { "u": "images/wissol/wissol-03.jpg", "t": "i", "wide": true },
    "prwissol5": { "u": "images/wissol/wissol-05.jpg", "t": "i", "wide": true },
    "prwissol6": { "u": "images/wissol/wissol-06.jpg", "t": "i" },
    "prvisah": { "u": "images/visa/visa-01.jpg", "t": "i" },
    "prvisa2": { "u": "images/visa/visa-02.jpg", "t": "i" },
    "prvisa3": { "u": "images/visa/visa-03.jpg", "t": "i" },
    "prvisa4": { "u": "images/visa/visa-04.jpg", "t": "i", "wide": true },
    "prvisa5": { "u": "images/visa/visa-05.jpg", "t": "i" },
    "prvisa6": { "u": "images/visa/visa-06.jpg", "t": "i" },
    "prvisa7": { "u": "images/visa/visa-07.jpg", "t": "i", "wide": true },
    "prvisa8": { "u": "images/visa/visa-08.jpg", "t": "i" },
    "prvisa9": { "u": "images/visa/visa-09.jpg", "t": "i" },
    "prafflelou1": { "u": "images/afflelou/afflelou-01.jpg", "t": "i" },
    "prafflelou2": { "u": "images/afflelou/afflelou-02.jpg", "t": "i" },
    "prafflelou3": { "u": "images/afflelou/afflelou-03.jpg", "t": "i" },
    "prafflelou4": { "u": "images/afflelou/afflelou-04.jpg", "t": "i" },
    "prtommyjeansh": { "u": "images/tommyjeans/tommyjeans-02.jpg", "t": "i" },
    "prtommyjeans1": { "u": "images/tommyjeans/tommyjeans-01.jpg", "t": "i", "wide": true },
    "prthebodyshoph": { "u": "images/thebodyshop/thebodyshop-02.jpg", "t": "i" },
    "prthebodyshop1": { "u": "images/thebodyshop/thebodyshop-01.jpg", "t": "i" },
    "prerborianh": { "u": "images/erborian/erborian-01.jpg", "t": "i" },
    "prerborian2": { "u": "images/erborian/erborian-02.jpg", "t": "i" },
    "prerborian3": { "u": "images/erborian/erborian-03.jpg", "t": "i" },
    "prerborian4": { "u": "images/erborian/erborian-04.jpg", "t": "i" },
    "prerborian5": { "u": "images/erborian/erborian-05.jpg", "t": "i" },
    "prerborian6": { "u": "images/erborian/erborian-06.jpg", "t": "i" },
    "prerborian7": { "u": "images/erborian/erborian-07.jpg", "t": "i" },
    "prerborian8": { "u": "images/erborian/erborian-08.jpg", "t": "i" },
    "prerborian9": { "u": "images/erborian/erborian-09.jpg", "t": "i" },
    "prmelvitah": { "u": "images/melvita/melvita-02.jpg", "t": "i" },
    "prmelvita1": { "u": "images/melvita/melvita-01.jpg", "t": "i" },
    "prmelvita3": { "u": "images/melvita/melvita-03.jpg", "t": "i" },
    "prmelvita4": { "u": "images/melvita/melvita-04.jpg", "t": "i", "wide": true },
    "prmelvita5": { "u": "images/melvita/melvita-05.jpg", "t": "i" },
    "prmelvita6": { "u": "images/melvita/melvita-06.jpg", "t": "i" },
    "prmonkeypopuph": { "u": "images/monkeyshoulder-popup/popup-01.jpg", "t": "i" },
    "prmonkeypopup2": { "u": "images/monkeyshoulder-popup/popup-02.jpg", "t": "i" },
    "prmonkeypopup3": { "u": "images/monkeyshoulder-popup/popup-03.jpg", "t": "i" },
    "prmonkeypopup4": { "u": "images/monkeyshoulder-popup/popup-04.jpg", "t": "i" },
    "prmonkeypopup5": { "u": "images/monkeyshoulder-popup/popup-05.jpg", "t": "i" },
    "prmonkeypopup6": { "u": "images/monkeyshoulder-popup/popup-06.jpg", "t": "i" },
    "prmonkeypopup7": { "u": "images/monkeyshoulder-popup/popup-07.jpg", "t": "i" },
    "prminih": { "u": "images/mini/mini-06.jpg", "t": "i" },
    "prmini1": { "u": "images/mini/mini-01.jpg", "t": "i" },
    "prmini2": { "u": "images/mini/mini-02.jpg", "t": "i" },
    "prmini3": { "u": "images/mini/mini-03.jpg", "t": "i" },
    "prmini4": { "u": "images/mini/mini-04.jpg", "t": "i" },
    "prmini5": { "u": "images/mini/mini-05.jpg", "t": "i" },
    "prmini7": { "u": "images/mini/mini-07.jpg", "t": "i", "wide": true },
    "prmini8": { "u": "images/mini/mini-08.jpg", "t": "i", "wide": true },
    "prmini9": { "u": "images/mini/mini-09.jpg", "t": "i", "wide": true },
    "prmini10": { "u": "images/mini/mini-10.jpg", "t": "i" },
    "prmini11": { "u": "images/mini/mini-11.jpg", "t": "i" },
    "prmini12": { "u": "images/mini/mini-12.jpg", "t": "i" },
    // CV link on the About and Contact pages. Upload your CV to the repo as cv.pdf.
    "cv": { "u": "cv.pdf", "t": "f" },
    "hlcberlinale1": { "u": "images/berlinale/berlinale-logo.jpg", "t": "i" },
    "hlcmonkey1": { "u": "images/monkeyshoulder/monkeyshoulder-logo.jpg", "t": "i" },
    "hlcbmwexp": { "u": "images/bmw/bmw-logo.svg", "t": "i" },
    "about": { "u": "images/me/portrait.jpg", "t": "i" },
    "prmoeth": { "u": "images/moet/moet-01.jpg", "t": "i" },
    "prmoet2": { "u": "images/moet/moet-02.jpg", "t": "i" },
    "prmoet3": { "u": "images/moet/moet-03.jpg", "t": "i" },
    "prmoet4": { "u": "images/moet/moet-04.jpg", "t": "i" },
    "prmoet5": { "u": "images/moet/moet-05.jpg", "t": "i" },
    "prmoet6": { "u": "images/moet/moet-06.jpg", "t": "i" },
    "prmoet7": { "u": "images/moet/moet-07.jpg", "t": "i" },
    "prmoet8": { "u": "images/moet/moet-08.jpg", "t": "i" },
    "prmoet9": { "u": "images/moet/moet-09.jpg", "t": "i" }
  }
};
